// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "exp_generic_double_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic exp_generic_double_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic exp_generic_double_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> exp_generic_double_s::ap_ST_fsm_pp0_stage0 = "1";
const bool exp_generic_double_s::ap_const_boolean_1 = true;
const sc_lv<32> exp_generic_double_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool exp_generic_double_s::ap_const_boolean_0 = false;
const sc_lv<32> exp_generic_double_s::ap_const_lv32_3F = "111111";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_34 = "110100";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_3E = "111110";
const sc_lv<11> exp_generic_double_s::ap_const_lv11_7FF = "11111111111";
const sc_lv<52> exp_generic_double_s::ap_const_lv52_0 = "0000000000000000000000000000000000000000000000000000";
const sc_lv<12> exp_generic_double_s::ap_const_lv12_C01 = "110000000001";
const sc_lv<2> exp_generic_double_s::ap_const_lv2_1 = "1";
const sc_lv<54> exp_generic_double_s::ap_const_lv54_0 = "000000000000000000000000000000000000000000000000000000";
const sc_lv<7> exp_generic_double_s::ap_const_lv7_0 = "0000000";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_B = "1011";
const sc_lv<11> exp_generic_double_s::ap_const_lv11_3FF = "1111111111";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_7 = "111";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_46 = "1000110";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_37 = "110111";
const sc_lv<18> exp_generic_double_s::ap_const_lv18_20000 = "100000000000000000";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_12 = "10010";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_1E = "11110";
const sc_lv<18> exp_generic_double_s::ap_const_lv18_0 = "000000000000000000";
const sc_lv<13> exp_generic_double_s::ap_const_lv13_1 = "1";
const sc_lv<12> exp_generic_double_s::ap_const_lv12_0 = "000000000000";
const sc_lv<84> exp_generic_double_s::ap_const_lv84_58B90BFBE8E7BCD5E4 = "10110001011100100001011111110111110100011100111101111001101010111100100";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_D = "1101";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_53 = "1010011";
const sc_lv<1> exp_generic_double_s::ap_const_lv1_0 = "0";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_33 = "110011";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_3A = "111010";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_2B = "101011";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_32 = "110010";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_23 = "100011";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_2A = "101010";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_1B = "11011";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_22 = "100010";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_10 = "10000";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_19 = "11001";
const sc_lv<9> exp_generic_double_s::ap_const_lv9_0 = "000000000";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_3B = "111011";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_4E = "1001110";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_2 = "10";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_29 = "101001";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_39 = "111001";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_5C = "1011100";
const sc_lv<2> exp_generic_double_s::ap_const_lv2_0 = "00";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_8 = "1000";
const sc_lv<59> exp_generic_double_s::ap_const_lv59_10 = "10000";
const sc_lv<49> exp_generic_double_s::ap_const_lv49_0 = "0000000000000000000000000000000000000000000000000";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_6A = "1101010";
const sc_lv<13> exp_generic_double_s::ap_const_lv13_1FFF = "1111111111111";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_A = "1010";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_C = "1100";
const sc_lv<3> exp_generic_double_s::ap_const_lv3_0 = "000";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_35 = "110101";
const sc_lv<64> exp_generic_double_s::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<64> exp_generic_double_s::ap_const_lv64_7FF0000000000000 = "111111111110000000000000000000000000000000000000000000000000000";
const sc_lv<13> exp_generic_double_s::ap_const_lv13_1C02 = "1110000000010";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_36 = "110110";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_69 = "1101001";
const sc_lv<32> exp_generic_double_s::ap_const_lv32_68 = "1101000";
const sc_lv<1> exp_generic_double_s::ap_const_lv1_1 = "1";
const sc_lv<64> exp_generic_double_s::ap_const_lv64_7FFFFFFFFFFFFFFF = "111111111111111111111111111111111111111111111111111111111111111";
const sc_lv<31> exp_generic_double_s::ap_const_lv31_5C55 = "101110001010101";

exp_generic_double_s::exp_generic_double_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    table_exp_Z1_array_s_U = new exp_generic_doublbkb("table_exp_Z1_array_s_U");
    table_exp_Z1_array_s_U->clk(ap_clk);
    table_exp_Z1_array_s_U->reset(ap_rst);
    table_exp_Z1_array_s_U->address0(table_exp_Z1_array_s_address0);
    table_exp_Z1_array_s_U->ce0(table_exp_Z1_array_s_ce0);
    table_exp_Z1_array_s_U->q0(table_exp_Z1_array_s_q0);
    table_f_Z3_array_V_U = new exp_generic_doublcud("table_f_Z3_array_V_U");
    table_f_Z3_array_V_U->clk(ap_clk);
    table_f_Z3_array_V_U->reset(ap_rst);
    table_f_Z3_array_V_U->address0(table_f_Z3_array_V_address0);
    table_f_Z3_array_V_U->ce0(table_f_Z3_array_V_ce0);
    table_f_Z3_array_V_U->q0(table_f_Z3_array_V_q0);
    table_f_Z3_array_V_U->address1(table_f_Z3_array_V_address1);
    table_f_Z3_array_V_U->ce1(table_f_Z3_array_V_ce1);
    table_f_Z3_array_V_U->q1(table_f_Z3_array_V_q1);
    table_f_Z2_array_V_U = new exp_generic_doubldEe("table_f_Z2_array_V_U");
    table_f_Z2_array_V_U->clk(ap_clk);
    table_f_Z2_array_V_U->reset(ap_rst);
    table_f_Z2_array_V_U->address0(table_f_Z2_array_V_address0);
    table_f_Z2_array_V_U->ce0(table_f_Z2_array_V_ce0);
    table_f_Z2_array_V_U->q0(table_f_Z2_array_V_q0);
    myip_v1_0_HLS_maceOg_U1 = new myip_v1_0_HLS_maceOg<1,1,16,16,19,31>("myip_v1_0_HLS_maceOg_U1");
    myip_v1_0_HLS_maceOg_U1->din0(grp_fu_1138_p0);
    myip_v1_0_HLS_maceOg_U1->din1(m_fix_hi_V_fu_449_p4);
    myip_v1_0_HLS_maceOg_U1->din2(rhs_V_fu_471_p3);
    myip_v1_0_HLS_maceOg_U1->dout(grp_fu_1138_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Z4_V_fu_628_p1);
    sensitive << ( ret_V_3_fu_592_p2 );

    SC_METHOD(thread_add_ln1146_1_fu_893_p2);
    sensitive << ( trunc_ln_fu_879_p3 );
    sensitive << ( zext_ln1146_fu_871_p1 );

    SC_METHOD(thread_add_ln657_2_fu_798_p2);
    sensitive << ( exp_Z2P_m_1_V_fu_730_p2 );
    sensitive << ( zext_ln657_2_fu_794_p1 );

    SC_METHOD(thread_add_ln657_fu_714_p2);
    sensitive << ( ret_V_4_fu_671_p2 );
    sensitive << ( zext_ln657_fu_710_p1 );

    SC_METHOD(thread_add_ln805_fu_508_p2);
    sensitive << ( tmp_5_fu_483_p4 );

    SC_METHOD(thread_and_ln18_fu_311_p2);
    sensitive << ( icmp_ln833_fu_287_p2 );
    sensitive << ( icmp_ln833_3_fu_305_p2 );

    SC_METHOD(thread_and_ln209_fu_299_p2);
    sensitive << ( icmp_ln833_fu_287_p2 );
    sensitive << ( icmp_ln837_fu_293_p2 );

    SC_METHOD(thread_and_ln338_1_fu_1061_p2);
    sensitive << ( icmp_ln338_reg_1184_pp0_iter4_reg );
    sensitive << ( xor_ln338_1_fu_1055_p2 );

    SC_METHOD(thread_and_ln338_fu_1019_p2);
    sensitive << ( icmp_ln338_reg_1184_pp0_iter4_reg );
    sensitive << ( or_ln338_fu_935_p2 );

    SC_METHOD(thread_and_ln849_fu_1029_p2);
    sensitive << ( icmp_ln849_fu_929_p2 );
    sensitive << ( xor_ln338_fu_1024_p2 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter5);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter6);

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_reg_pp0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter6 );

    SC_METHOD(thread_ap_idle_pp0_0to5);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_reset_idle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_idle_pp0_0to5 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( sel_tmp16_reg_1280 );
    sensitive << ( select_ln214_2_fu_1125_p3 );

    SC_METHOD(thread_bitcast_ln512_fu_1009_p1);
    sensitive << ( p_Result_24_fu_999_p4 );

    SC_METHOD(thread_e_frac_V_fu_335_p2);
    sensitive << ( p_Result_s_fu_327_p3 );

    SC_METHOD(thread_exp_Z1P_m_1_l_V_fu_808_p2);
    sensitive << ( zext_ln682_fu_790_p1 );
    sensitive << ( zext_ln657_3_fu_804_p1 );

    SC_METHOD(thread_exp_Z2P_m_1_V_fu_730_p2);
    sensitive << ( ret_V_5_fu_724_p1 );
    sensitive << ( zext_ln657_1_fu_727_p1 );

    SC_METHOD(thread_f_Z4_V_fu_654_p4);
    sensitive << ( table_f_Z3_array_V_q0 );

    SC_METHOD(thread_grp_fu_1138_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_icmp_ln338_1_fu_552_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( sext_ln682_fu_357_p1 );
    sensitive << ( shl_ln_fu_544_p3 );

    SC_METHOD(thread_icmp_ln338_fu_530_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( m_exp_fu_321_p2 );

    SC_METHOD(thread_icmp_ln805_fu_502_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( trunc_ln805_fu_499_p1 );

    SC_METHOD(thread_icmp_ln833_3_fu_305_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_V_3_fu_283_p1 );

    SC_METHOD(thread_icmp_ln833_fu_287_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_V_fu_273_p4 );

    SC_METHOD(thread_icmp_ln837_fu_293_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_V_3_fu_283_p1 );

    SC_METHOD(thread_icmp_ln849_fu_929_p2);
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_8_fu_919_p4 );

    SC_METHOD(thread_icmp_ln853_fu_955_p2);
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( r_exp_V_2_fu_912_p3 );

    SC_METHOD(thread_isNeg_fu_361_p3);
    sensitive << ( m_exp_fu_321_p2 );

    SC_METHOD(thread_lhs_V_1_fu_664_p1);
    sensitive << ( Z4_V_reg_1215_pp0_iter2_reg );

    SC_METHOD(thread_lhs_V_2_fu_779_p5);
    sensitive << ( Z2_V_reg_1202_pp0_iter3_reg );
    sensitive << ( tmp_1_fu_736_p4 );

    SC_METHOD(thread_lhs_V_3_fu_838_p1);
    sensitive << ( exp_Z1_V_reg_1255 );

    SC_METHOD(thread_lhs_V_4_fu_859_p3);
    sensitive << ( ret_V_6_fu_841_p2 );

    SC_METHOD(thread_lhs_V_fu_567_p1);
    sensitive << ( r_V_13_reg_1172 );

    SC_METHOD(thread_lshr_ln662_6_fu_746_p4);
    sensitive << ( Z2_V_reg_1202_pp0_iter3_reg );
    sensitive << ( tmp_1_fu_736_p4 );

    SC_METHOD(thread_m_exp_2_fu_379_p3);
    sensitive << ( m_exp_fu_321_p2 );
    sensitive << ( isNeg_fu_361_p3 );
    sensitive << ( sext_ln1311_fu_375_p1 );

    SC_METHOD(thread_m_exp_fu_321_p2);
    sensitive << ( zext_ln502_fu_317_p1 );

    SC_METHOD(thread_m_fix_hi_V_fu_449_p4);
    sensitive << ( r_V_13_fu_415_p3 );

    SC_METHOD(thread_m_fix_l_V_fu_423_p4);
    sensitive << ( r_V_13_fu_415_p3 );

    SC_METHOD(thread_m_frac_l_V_fu_349_p3);
    sensitive << ( select_ln253_fu_341_p3 );

    SC_METHOD(thread_or_ln214_1_fu_834_p2);
    sensitive << ( and_ln209_reg_1154_pp0_iter4_reg );
    sensitive << ( and_ln18_reg_1161_pp0_iter4_reg );

    SC_METHOD(thread_or_ln214_fu_1105_p2);
    sensitive << ( and_ln209_reg_1154_pp0_iter5_reg );
    sensitive << ( x_is_pinf_fu_1100_p2 );

    SC_METHOD(thread_or_ln338_fu_935_p2);
    sensitive << ( icmp_ln338_1_reg_1192_pp0_iter4_reg );
    sensitive << ( icmp_ln849_fu_929_p2 );

    SC_METHOD(thread_or_ln849_1_fu_1066_p2);
    sensitive << ( icmp_ln338_reg_1184_pp0_iter4_reg );
    sensitive << ( icmp_ln849_fu_929_p2 );

    SC_METHOD(thread_or_ln849_2_fu_1077_p2);
    sensitive << ( and_ln338_1_fu_1061_p2 );
    sensitive << ( xor_ln849_fu_1071_p2 );

    SC_METHOD(thread_or_ln849_fu_1035_p2);
    sensitive << ( and_ln338_fu_1019_p2 );
    sensitive << ( and_ln849_fu_1029_p2 );

    SC_METHOD(thread_out_exp_V_fu_993_p2);
    sensitive << ( trunc_ln168_fu_989_p1 );

    SC_METHOD(thread_p_Result_15_fu_492_p3);
    sensitive << ( grp_fu_1138_p3 );

    SC_METHOD(thread_p_Result_22_fu_265_p3);
    sensitive << ( p_Val2_s_fu_261_p1 );

    SC_METHOD(thread_p_Result_23_fu_459_p3);
    sensitive << ( r_V_13_fu_415_p3 );

    SC_METHOD(thread_p_Result_24_fu_999_p4);
    sensitive << ( out_exp_V_fu_993_p2 );
    sensitive << ( tmp_V_4_fu_981_p3 );

    SC_METHOD(thread_p_Result_s_fu_327_p3);
    sensitive << ( tmp_V_3_fu_283_p1 );

    SC_METHOD(thread_p_Val2_s_fu_261_p1);
    sensitive << ( x );

    SC_METHOD(thread_r_V_13_fu_415_p3);
    sensitive << ( isNeg_fu_361_p3 );
    sensitive << ( sext_ln1287_fu_405_p1 );
    sensitive << ( r_V_1_fu_409_p2 );

    SC_METHOD(thread_r_V_15_fu_561_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( r_exp_V_3_reg_1177 );

    SC_METHOD(thread_r_V_15_fu_561_p2);
    sensitive << ( r_V_15_fu_561_p1 );

    SC_METHOD(thread_r_V_16_fu_694_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( r_V_16_fu_694_p00 );

    SC_METHOD(thread_r_V_16_fu_694_p00);
    sensitive << ( ret_V_4_fu_671_p2 );

    SC_METHOD(thread_r_V_16_fu_694_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( r_V_16_fu_694_p10 );

    SC_METHOD(thread_r_V_16_fu_694_p10);
    sensitive << ( tmp_i_fu_677_p4 );

    SC_METHOD(thread_r_V_16_fu_694_p2);
    sensitive << ( r_V_16_fu_694_p0 );
    sensitive << ( r_V_16_fu_694_p1 );

    SC_METHOD(thread_r_V_17_fu_763_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( r_V_17_fu_763_p00 );

    SC_METHOD(thread_r_V_17_fu_763_p00);
    sensitive << ( exp_Z2P_m_1_V_fu_730_p2 );

    SC_METHOD(thread_r_V_17_fu_763_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( r_V_17_fu_763_p10 );

    SC_METHOD(thread_r_V_17_fu_763_p10);
    sensitive << ( lshr_ln662_6_fu_746_p4 );

    SC_METHOD(thread_r_V_17_fu_763_p2);
    sensitive << ( r_V_17_fu_763_p0 );
    sensitive << ( r_V_17_fu_763_p1 );

    SC_METHOD(thread_r_V_18_fu_853_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( r_V_18_fu_853_p00 );

    SC_METHOD(thread_r_V_18_fu_853_p00);
    sensitive << ( exp_Z1P_m_1_V_reg_1260 );

    SC_METHOD(thread_r_V_18_fu_853_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( r_V_18_fu_853_p10 );

    SC_METHOD(thread_r_V_18_fu_853_p10);
    sensitive << ( exp_Z1_hi_V_reg_1265 );

    SC_METHOD(thread_r_V_18_fu_853_p2);
    sensitive << ( r_V_18_fu_853_p0 );
    sensitive << ( r_V_18_fu_853_p1 );

    SC_METHOD(thread_r_V_1_fu_409_p2);
    sensitive << ( sext_ln682_fu_357_p1 );
    sensitive << ( zext_ln1287_fu_391_p1 );

    SC_METHOD(thread_r_V_3_fu_437_p2);
    sensitive << ( m_fix_l_V_fu_423_p4 );
    sensitive << ( zext_ln1253_fu_433_p1 );

    SC_METHOD(thread_r_V_4_fu_443_p2);
    sensitive << ( m_fix_l_V_fu_423_p4 );
    sensitive << ( zext_ln1253_fu_433_p1 );

    SC_METHOD(thread_r_V_fu_399_p2);
    sensitive << ( m_frac_l_V_fu_349_p3 );
    sensitive << ( zext_ln1285_fu_395_p1 );

    SC_METHOD(thread_r_exp_V_2_fu_912_p3);
    sensitive << ( r_exp_V_3_reg_1177_pp0_iter4_reg );
    sensitive << ( tmp_7_fu_899_p3 );
    sensitive << ( r_exp_V_fu_907_p2 );

    SC_METHOD(thread_r_exp_V_3_fu_522_p3);
    sensitive << ( tmp_5_fu_483_p4 );
    sensitive << ( p_Result_15_fu_492_p3 );
    sensitive << ( select_ln805_fu_514_p3 );

    SC_METHOD(thread_r_exp_V_fu_907_p2);
    sensitive << ( r_exp_V_3_reg_1177_pp0_iter4_reg );

    SC_METHOD(thread_ret_V_3_fu_592_p2);
    sensitive << ( lhs_V_fu_567_p1 );
    sensitive << ( sext_ln682_2_fu_588_p1 );

    SC_METHOD(thread_ret_V_4_fu_671_p2);
    sensitive << ( rhs_V_2_fu_667_p1 );
    sensitive << ( lhs_V_1_fu_664_p1 );

    SC_METHOD(thread_ret_V_5_fu_724_p1);
    sensitive << ( tmp_i_reg_1240 );

    SC_METHOD(thread_ret_V_6_fu_841_p2);
    sensitive << ( lhs_V_3_fu_838_p1 );

    SC_METHOD(thread_ret_V_7_fu_887_p2);
    sensitive << ( zext_ln657_5_fu_867_p1 );
    sensitive << ( lhs_V_4_fu_859_p3 );

    SC_METHOD(thread_rhs_V_1_fu_580_p3);
    sensitive << ( tmp_9_fu_570_p4 );

    SC_METHOD(thread_rhs_V_2_fu_667_p1);
    sensitive << ( f_Z4_V_fu_654_p4 );

    SC_METHOD(thread_rhs_V_fu_471_p3);
    sensitive << ( p_Result_23_fu_459_p3 );

    SC_METHOD(thread_sel_tmp16_fu_1089_p2);
    sensitive << ( tmp19_fu_1083_p2 );
    sensitive << ( icmp_ln853_fu_955_p2 );

    SC_METHOD(thread_sel_tmp5_fu_1041_p2);
    sensitive << ( or_ln849_fu_1035_p2 );
    sensitive << ( xor_ln214_fu_1013_p2 );

    SC_METHOD(thread_sel_tmp6_fu_1047_p3);
    sensitive << ( sel_tmp5_fu_1041_p2 );
    sensitive << ( select_ln339_fu_947_p3 );
    sensitive << ( bitcast_ln512_fu_1009_p1 );

    SC_METHOD(thread_select_ln1322_fu_536_p3);
    sensitive << ( isNeg_fu_361_p3 );
    sensitive << ( r_V_3_fu_437_p2 );
    sensitive << ( r_V_4_fu_443_p2 );

    SC_METHOD(thread_select_ln214_1_fu_1117_p3);
    sensitive << ( or_ln214_fu_1105_p2 );
    sensitive << ( select_ln214_fu_1110_p3 );

    SC_METHOD(thread_select_ln214_2_fu_1125_p3);
    sensitive << ( or_ln214_1_reg_1270 );
    sensitive << ( sel_tmp6_reg_1275 );
    sensitive << ( select_ln214_1_fu_1117_p3 );

    SC_METHOD(thread_select_ln214_fu_1110_p3);
    sensitive << ( and_ln209_reg_1154_pp0_iter5_reg );

    SC_METHOD(thread_select_ln253_fu_341_p3);
    sensitive << ( p_Result_22_fu_265_p3 );
    sensitive << ( p_Result_s_fu_327_p3 );
    sensitive << ( e_frac_V_fu_335_p2 );

    SC_METHOD(thread_select_ln339_fu_947_p3);
    sensitive << ( tmp_10_fu_940_p3 );

    SC_METHOD(thread_select_ln805_fu_514_p3);
    sensitive << ( tmp_5_fu_483_p4 );
    sensitive << ( icmp_ln805_fu_502_p2 );
    sensitive << ( add_ln805_fu_508_p2 );

    SC_METHOD(thread_sext_ln1287_fu_405_p1);
    sensitive << ( r_V_fu_399_p2 );

    SC_METHOD(thread_sext_ln1311_1_fu_387_p1);
    sensitive << ( m_exp_2_fu_379_p3 );

    SC_METHOD(thread_sext_ln1311_fu_375_p1);
    sensitive << ( sub_ln1311_fu_369_p2 );

    SC_METHOD(thread_sext_ln682_2_fu_588_p1);
    sensitive << ( rhs_V_1_fu_580_p3 );

    SC_METHOD(thread_sext_ln682_fu_357_p1);
    sensitive << ( m_frac_l_V_fu_349_p3 );

    SC_METHOD(thread_shl_ln_fu_544_p3);
    sensitive << ( select_ln1322_fu_536_p3 );

    SC_METHOD(thread_sub_ln1311_fu_369_p2);
    sensitive << ( tmp_V_fu_273_p4 );

    SC_METHOD(thread_table_exp_Z1_array_s_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( zext_ln498_fu_650_p1 );

    SC_METHOD(thread_table_exp_Z1_array_s_ce0);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_table_f_Z2_array_V_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( zext_ln498_3_fu_720_p1 );

    SC_METHOD(thread_table_f_Z2_array_V_ce0);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_table_f_Z3_array_V_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( zext_ln498_1_fu_642_p1 );

    SC_METHOD(thread_table_f_Z3_array_V_address1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( zext_ln498_2_fu_646_p1 );

    SC_METHOD(thread_table_f_Z3_array_V_ce0);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_table_f_Z3_array_V_ce1);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_tmp19_fu_1083_p2);
    sensitive << ( xor_ln214_fu_1013_p2 );
    sensitive << ( or_ln849_2_fu_1077_p2 );

    SC_METHOD(thread_tmp_10_fu_940_p3);
    sensitive << ( select_ln253_reg_1167_pp0_iter4_reg );

    SC_METHOD(thread_tmp_1_fu_736_p4);
    sensitive << ( table_f_Z2_array_V_q0 );

    SC_METHOD(thread_tmp_2_fu_769_p4);
    sensitive << ( r_V_17_fu_763_p2 );

    SC_METHOD(thread_tmp_5_fu_483_p4);
    sensitive << ( grp_fu_1138_p3 );

    SC_METHOD(thread_tmp_6_fu_971_p4);
    sensitive << ( ret_V_7_fu_887_p2 );

    SC_METHOD(thread_tmp_7_fu_899_p3);
    sensitive << ( add_ln1146_1_fu_893_p2 );

    SC_METHOD(thread_tmp_8_fu_919_p4);
    sensitive << ( r_exp_V_2_fu_912_p3 );

    SC_METHOD(thread_tmp_9_fu_570_p4);
    sensitive << ( r_V_15_fu_561_p2 );

    SC_METHOD(thread_tmp_V_3_fu_283_p1);
    sensitive << ( p_Val2_s_fu_261_p1 );

    SC_METHOD(thread_tmp_V_4_fu_981_p3);
    sensitive << ( tmp_7_fu_899_p3 );
    sensitive << ( tmp_fu_961_p4 );
    sensitive << ( tmp_6_fu_971_p4 );

    SC_METHOD(thread_tmp_V_fu_273_p4);
    sensitive << ( p_Val2_s_fu_261_p1 );

    SC_METHOD(thread_tmp_fu_961_p4);
    sensitive << ( ret_V_7_fu_887_p2 );

    SC_METHOD(thread_tmp_i_fu_677_p4);
    sensitive << ( table_f_Z3_array_V_q1 );
    sensitive << ( Z3_V_reg_1209_pp0_iter2_reg );

    SC_METHOD(thread_tmp_s_fu_700_p4);
    sensitive << ( r_V_16_fu_694_p2 );

    SC_METHOD(thread_trunc_ln1146_fu_875_p1);
    sensitive << ( ret_V_6_fu_841_p2 );

    SC_METHOD(thread_trunc_ln168_fu_989_p1);
    sensitive << ( r_exp_V_2_fu_912_p3 );

    SC_METHOD(thread_trunc_ln805_fu_499_p1);
    sensitive << ( grp_fu_1138_p3 );

    SC_METHOD(thread_trunc_ln_fu_879_p3);
    sensitive << ( trunc_ln1146_fu_875_p1 );

    SC_METHOD(thread_x_is_pinf_fu_1100_p2);
    sensitive << ( and_ln18_reg_1161_pp0_iter5_reg );
    sensitive << ( xor_ln936_fu_1095_p2 );

    SC_METHOD(thread_xor_ln214_fu_1013_p2);
    sensitive << ( or_ln214_1_fu_834_p2 );

    SC_METHOD(thread_xor_ln338_1_fu_1055_p2);
    sensitive << ( or_ln338_fu_935_p2 );

    SC_METHOD(thread_xor_ln338_fu_1024_p2);
    sensitive << ( icmp_ln338_reg_1184_pp0_iter4_reg );

    SC_METHOD(thread_xor_ln849_fu_1071_p2);
    sensitive << ( or_ln849_1_fu_1066_p2 );

    SC_METHOD(thread_xor_ln936_fu_1095_p2);
    sensitive << ( p_Result_22_reg_1149_pp0_iter5_reg );

    SC_METHOD(thread_zext_ln1146_fu_871_p1);
    sensitive << ( r_V_18_fu_853_p2 );

    SC_METHOD(thread_zext_ln1253_fu_433_p1);
    sensitive << ( sext_ln1311_1_fu_387_p1 );

    SC_METHOD(thread_zext_ln1285_fu_395_p1);
    sensitive << ( sext_ln1311_1_fu_387_p1 );

    SC_METHOD(thread_zext_ln1287_fu_391_p1);
    sensitive << ( sext_ln1311_1_fu_387_p1 );

    SC_METHOD(thread_zext_ln498_1_fu_642_p1);
    sensitive << ( Z4_ind_V_reg_1220 );

    SC_METHOD(thread_zext_ln498_2_fu_646_p1);
    sensitive << ( Z3_V_reg_1209 );

    SC_METHOD(thread_zext_ln498_3_fu_720_p1);
    sensitive << ( Z2_V_reg_1202_pp0_iter2_reg );

    SC_METHOD(thread_zext_ln498_fu_650_p1);
    sensitive << ( m_diff_hi_V_reg_1197_pp0_iter2_reg );

    SC_METHOD(thread_zext_ln502_fu_317_p1);
    sensitive << ( tmp_V_fu_273_p4 );

    SC_METHOD(thread_zext_ln657_1_fu_727_p1);
    sensitive << ( add_ln657_reg_1245 );

    SC_METHOD(thread_zext_ln657_2_fu_794_p1);
    sensitive << ( tmp_2_fu_769_p4 );

    SC_METHOD(thread_zext_ln657_3_fu_804_p1);
    sensitive << ( add_ln657_2_fu_798_p2 );

    SC_METHOD(thread_zext_ln657_5_fu_867_p1);
    sensitive << ( r_V_18_fu_853_p2 );

    SC_METHOD(thread_zext_ln657_fu_710_p1);
    sensitive << ( tmp_s_fu_700_p4 );

    SC_METHOD(thread_zext_ln682_fu_790_p1);
    sensitive << ( lhs_V_2_fu_779_p5 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_reset_idle_pp0 );

    ap_CS_fsm = "1";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter6 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "exp_generic_double_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, x, "(port)x");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter6, "ap_enable_reg_pp0_iter6");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2, "ap_block_state3_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3, "ap_block_state4_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter4, "ap_block_state5_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter5, "ap_block_state6_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter6, "ap_block_state7_pp0_stage0_iter6");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, table_exp_Z1_array_s_address0, "table_exp_Z1_array_s_address0");
    sc_trace(mVcdFile, table_exp_Z1_array_s_ce0, "table_exp_Z1_array_s_ce0");
    sc_trace(mVcdFile, table_exp_Z1_array_s_q0, "table_exp_Z1_array_s_q0");
    sc_trace(mVcdFile, table_f_Z3_array_V_address0, "table_f_Z3_array_V_address0");
    sc_trace(mVcdFile, table_f_Z3_array_V_ce0, "table_f_Z3_array_V_ce0");
    sc_trace(mVcdFile, table_f_Z3_array_V_q0, "table_f_Z3_array_V_q0");
    sc_trace(mVcdFile, table_f_Z3_array_V_address1, "table_f_Z3_array_V_address1");
    sc_trace(mVcdFile, table_f_Z3_array_V_ce1, "table_f_Z3_array_V_ce1");
    sc_trace(mVcdFile, table_f_Z3_array_V_q1, "table_f_Z3_array_V_q1");
    sc_trace(mVcdFile, table_f_Z2_array_V_address0, "table_f_Z2_array_V_address0");
    sc_trace(mVcdFile, table_f_Z2_array_V_ce0, "table_f_Z2_array_V_ce0");
    sc_trace(mVcdFile, table_f_Z2_array_V_q0, "table_f_Z2_array_V_q0");
    sc_trace(mVcdFile, p_Result_22_fu_265_p3, "p_Result_22_fu_265_p3");
    sc_trace(mVcdFile, p_Result_22_reg_1149, "p_Result_22_reg_1149");
    sc_trace(mVcdFile, p_Result_22_reg_1149_pp0_iter1_reg, "p_Result_22_reg_1149_pp0_iter1_reg");
    sc_trace(mVcdFile, p_Result_22_reg_1149_pp0_iter2_reg, "p_Result_22_reg_1149_pp0_iter2_reg");
    sc_trace(mVcdFile, p_Result_22_reg_1149_pp0_iter3_reg, "p_Result_22_reg_1149_pp0_iter3_reg");
    sc_trace(mVcdFile, p_Result_22_reg_1149_pp0_iter4_reg, "p_Result_22_reg_1149_pp0_iter4_reg");
    sc_trace(mVcdFile, p_Result_22_reg_1149_pp0_iter5_reg, "p_Result_22_reg_1149_pp0_iter5_reg");
    sc_trace(mVcdFile, and_ln209_fu_299_p2, "and_ln209_fu_299_p2");
    sc_trace(mVcdFile, and_ln209_reg_1154, "and_ln209_reg_1154");
    sc_trace(mVcdFile, and_ln209_reg_1154_pp0_iter1_reg, "and_ln209_reg_1154_pp0_iter1_reg");
    sc_trace(mVcdFile, and_ln209_reg_1154_pp0_iter2_reg, "and_ln209_reg_1154_pp0_iter2_reg");
    sc_trace(mVcdFile, and_ln209_reg_1154_pp0_iter3_reg, "and_ln209_reg_1154_pp0_iter3_reg");
    sc_trace(mVcdFile, and_ln209_reg_1154_pp0_iter4_reg, "and_ln209_reg_1154_pp0_iter4_reg");
    sc_trace(mVcdFile, and_ln209_reg_1154_pp0_iter5_reg, "and_ln209_reg_1154_pp0_iter5_reg");
    sc_trace(mVcdFile, and_ln18_fu_311_p2, "and_ln18_fu_311_p2");
    sc_trace(mVcdFile, and_ln18_reg_1161, "and_ln18_reg_1161");
    sc_trace(mVcdFile, and_ln18_reg_1161_pp0_iter1_reg, "and_ln18_reg_1161_pp0_iter1_reg");
    sc_trace(mVcdFile, and_ln18_reg_1161_pp0_iter2_reg, "and_ln18_reg_1161_pp0_iter2_reg");
    sc_trace(mVcdFile, and_ln18_reg_1161_pp0_iter3_reg, "and_ln18_reg_1161_pp0_iter3_reg");
    sc_trace(mVcdFile, and_ln18_reg_1161_pp0_iter4_reg, "and_ln18_reg_1161_pp0_iter4_reg");
    sc_trace(mVcdFile, and_ln18_reg_1161_pp0_iter5_reg, "and_ln18_reg_1161_pp0_iter5_reg");
    sc_trace(mVcdFile, select_ln253_fu_341_p3, "select_ln253_fu_341_p3");
    sc_trace(mVcdFile, select_ln253_reg_1167, "select_ln253_reg_1167");
    sc_trace(mVcdFile, select_ln253_reg_1167_pp0_iter1_reg, "select_ln253_reg_1167_pp0_iter1_reg");
    sc_trace(mVcdFile, select_ln253_reg_1167_pp0_iter2_reg, "select_ln253_reg_1167_pp0_iter2_reg");
    sc_trace(mVcdFile, select_ln253_reg_1167_pp0_iter3_reg, "select_ln253_reg_1167_pp0_iter3_reg");
    sc_trace(mVcdFile, select_ln253_reg_1167_pp0_iter4_reg, "select_ln253_reg_1167_pp0_iter4_reg");
    sc_trace(mVcdFile, r_V_13_fu_415_p3, "r_V_13_fu_415_p3");
    sc_trace(mVcdFile, r_V_13_reg_1172, "r_V_13_reg_1172");
    sc_trace(mVcdFile, r_exp_V_3_fu_522_p3, "r_exp_V_3_fu_522_p3");
    sc_trace(mVcdFile, r_exp_V_3_reg_1177, "r_exp_V_3_reg_1177");
    sc_trace(mVcdFile, r_exp_V_3_reg_1177_pp0_iter1_reg, "r_exp_V_3_reg_1177_pp0_iter1_reg");
    sc_trace(mVcdFile, r_exp_V_3_reg_1177_pp0_iter2_reg, "r_exp_V_3_reg_1177_pp0_iter2_reg");
    sc_trace(mVcdFile, r_exp_V_3_reg_1177_pp0_iter3_reg, "r_exp_V_3_reg_1177_pp0_iter3_reg");
    sc_trace(mVcdFile, r_exp_V_3_reg_1177_pp0_iter4_reg, "r_exp_V_3_reg_1177_pp0_iter4_reg");
    sc_trace(mVcdFile, icmp_ln338_fu_530_p2, "icmp_ln338_fu_530_p2");
    sc_trace(mVcdFile, icmp_ln338_reg_1184, "icmp_ln338_reg_1184");
    sc_trace(mVcdFile, icmp_ln338_reg_1184_pp0_iter1_reg, "icmp_ln338_reg_1184_pp0_iter1_reg");
    sc_trace(mVcdFile, icmp_ln338_reg_1184_pp0_iter2_reg, "icmp_ln338_reg_1184_pp0_iter2_reg");
    sc_trace(mVcdFile, icmp_ln338_reg_1184_pp0_iter3_reg, "icmp_ln338_reg_1184_pp0_iter3_reg");
    sc_trace(mVcdFile, icmp_ln338_reg_1184_pp0_iter4_reg, "icmp_ln338_reg_1184_pp0_iter4_reg");
    sc_trace(mVcdFile, icmp_ln338_1_fu_552_p2, "icmp_ln338_1_fu_552_p2");
    sc_trace(mVcdFile, icmp_ln338_1_reg_1192, "icmp_ln338_1_reg_1192");
    sc_trace(mVcdFile, icmp_ln338_1_reg_1192_pp0_iter1_reg, "icmp_ln338_1_reg_1192_pp0_iter1_reg");
    sc_trace(mVcdFile, icmp_ln338_1_reg_1192_pp0_iter2_reg, "icmp_ln338_1_reg_1192_pp0_iter2_reg");
    sc_trace(mVcdFile, icmp_ln338_1_reg_1192_pp0_iter3_reg, "icmp_ln338_1_reg_1192_pp0_iter3_reg");
    sc_trace(mVcdFile, icmp_ln338_1_reg_1192_pp0_iter4_reg, "icmp_ln338_1_reg_1192_pp0_iter4_reg");
    sc_trace(mVcdFile, m_diff_hi_V_reg_1197, "m_diff_hi_V_reg_1197");
    sc_trace(mVcdFile, m_diff_hi_V_reg_1197_pp0_iter2_reg, "m_diff_hi_V_reg_1197_pp0_iter2_reg");
    sc_trace(mVcdFile, Z2_V_reg_1202, "Z2_V_reg_1202");
    sc_trace(mVcdFile, Z2_V_reg_1202_pp0_iter2_reg, "Z2_V_reg_1202_pp0_iter2_reg");
    sc_trace(mVcdFile, Z2_V_reg_1202_pp0_iter3_reg, "Z2_V_reg_1202_pp0_iter3_reg");
    sc_trace(mVcdFile, Z3_V_reg_1209, "Z3_V_reg_1209");
    sc_trace(mVcdFile, Z3_V_reg_1209_pp0_iter2_reg, "Z3_V_reg_1209_pp0_iter2_reg");
    sc_trace(mVcdFile, Z4_V_fu_628_p1, "Z4_V_fu_628_p1");
    sc_trace(mVcdFile, Z4_V_reg_1215, "Z4_V_reg_1215");
    sc_trace(mVcdFile, Z4_V_reg_1215_pp0_iter2_reg, "Z4_V_reg_1215_pp0_iter2_reg");
    sc_trace(mVcdFile, Z4_ind_V_reg_1220, "Z4_ind_V_reg_1220");
    sc_trace(mVcdFile, tmp_i_fu_677_p4, "tmp_i_fu_677_p4");
    sc_trace(mVcdFile, tmp_i_reg_1240, "tmp_i_reg_1240");
    sc_trace(mVcdFile, add_ln657_fu_714_p2, "add_ln657_fu_714_p2");
    sc_trace(mVcdFile, add_ln657_reg_1245, "add_ln657_reg_1245");
    sc_trace(mVcdFile, exp_Z1_V_reg_1255, "exp_Z1_V_reg_1255");
    sc_trace(mVcdFile, exp_Z1P_m_1_V_reg_1260, "exp_Z1P_m_1_V_reg_1260");
    sc_trace(mVcdFile, exp_Z1_hi_V_reg_1265, "exp_Z1_hi_V_reg_1265");
    sc_trace(mVcdFile, or_ln214_1_fu_834_p2, "or_ln214_1_fu_834_p2");
    sc_trace(mVcdFile, or_ln214_1_reg_1270, "or_ln214_1_reg_1270");
    sc_trace(mVcdFile, sel_tmp6_fu_1047_p3, "sel_tmp6_fu_1047_p3");
    sc_trace(mVcdFile, sel_tmp6_reg_1275, "sel_tmp6_reg_1275");
    sc_trace(mVcdFile, sel_tmp16_fu_1089_p2, "sel_tmp16_fu_1089_p2");
    sc_trace(mVcdFile, sel_tmp16_reg_1280, "sel_tmp16_reg_1280");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, zext_ln498_1_fu_642_p1, "zext_ln498_1_fu_642_p1");
    sc_trace(mVcdFile, zext_ln498_2_fu_646_p1, "zext_ln498_2_fu_646_p1");
    sc_trace(mVcdFile, zext_ln498_fu_650_p1, "zext_ln498_fu_650_p1");
    sc_trace(mVcdFile, zext_ln498_3_fu_720_p1, "zext_ln498_3_fu_720_p1");
    sc_trace(mVcdFile, p_Val2_s_fu_261_p1, "p_Val2_s_fu_261_p1");
    sc_trace(mVcdFile, tmp_V_fu_273_p4, "tmp_V_fu_273_p4");
    sc_trace(mVcdFile, tmp_V_3_fu_283_p1, "tmp_V_3_fu_283_p1");
    sc_trace(mVcdFile, icmp_ln833_fu_287_p2, "icmp_ln833_fu_287_p2");
    sc_trace(mVcdFile, icmp_ln837_fu_293_p2, "icmp_ln837_fu_293_p2");
    sc_trace(mVcdFile, icmp_ln833_3_fu_305_p2, "icmp_ln833_3_fu_305_p2");
    sc_trace(mVcdFile, zext_ln502_fu_317_p1, "zext_ln502_fu_317_p1");
    sc_trace(mVcdFile, p_Result_s_fu_327_p3, "p_Result_s_fu_327_p3");
    sc_trace(mVcdFile, e_frac_V_fu_335_p2, "e_frac_V_fu_335_p2");
    sc_trace(mVcdFile, m_frac_l_V_fu_349_p3, "m_frac_l_V_fu_349_p3");
    sc_trace(mVcdFile, m_exp_fu_321_p2, "m_exp_fu_321_p2");
    sc_trace(mVcdFile, sub_ln1311_fu_369_p2, "sub_ln1311_fu_369_p2");
    sc_trace(mVcdFile, isNeg_fu_361_p3, "isNeg_fu_361_p3");
    sc_trace(mVcdFile, sext_ln1311_fu_375_p1, "sext_ln1311_fu_375_p1");
    sc_trace(mVcdFile, m_exp_2_fu_379_p3, "m_exp_2_fu_379_p3");
    sc_trace(mVcdFile, sext_ln1311_1_fu_387_p1, "sext_ln1311_1_fu_387_p1");
    sc_trace(mVcdFile, zext_ln1285_fu_395_p1, "zext_ln1285_fu_395_p1");
    sc_trace(mVcdFile, r_V_fu_399_p2, "r_V_fu_399_p2");
    sc_trace(mVcdFile, sext_ln682_fu_357_p1, "sext_ln682_fu_357_p1");
    sc_trace(mVcdFile, zext_ln1287_fu_391_p1, "zext_ln1287_fu_391_p1");
    sc_trace(mVcdFile, sext_ln1287_fu_405_p1, "sext_ln1287_fu_405_p1");
    sc_trace(mVcdFile, r_V_1_fu_409_p2, "r_V_1_fu_409_p2");
    sc_trace(mVcdFile, m_fix_l_V_fu_423_p4, "m_fix_l_V_fu_423_p4");
    sc_trace(mVcdFile, zext_ln1253_fu_433_p1, "zext_ln1253_fu_433_p1");
    sc_trace(mVcdFile, m_fix_hi_V_fu_449_p4, "m_fix_hi_V_fu_449_p4");
    sc_trace(mVcdFile, p_Result_23_fu_459_p3, "p_Result_23_fu_459_p3");
    sc_trace(mVcdFile, rhs_V_fu_471_p3, "rhs_V_fu_471_p3");
    sc_trace(mVcdFile, grp_fu_1138_p3, "grp_fu_1138_p3");
    sc_trace(mVcdFile, trunc_ln805_fu_499_p1, "trunc_ln805_fu_499_p1");
    sc_trace(mVcdFile, tmp_5_fu_483_p4, "tmp_5_fu_483_p4");
    sc_trace(mVcdFile, icmp_ln805_fu_502_p2, "icmp_ln805_fu_502_p2");
    sc_trace(mVcdFile, add_ln805_fu_508_p2, "add_ln805_fu_508_p2");
    sc_trace(mVcdFile, p_Result_15_fu_492_p3, "p_Result_15_fu_492_p3");
    sc_trace(mVcdFile, select_ln805_fu_514_p3, "select_ln805_fu_514_p3");
    sc_trace(mVcdFile, r_V_3_fu_437_p2, "r_V_3_fu_437_p2");
    sc_trace(mVcdFile, r_V_4_fu_443_p2, "r_V_4_fu_443_p2");
    sc_trace(mVcdFile, select_ln1322_fu_536_p3, "select_ln1322_fu_536_p3");
    sc_trace(mVcdFile, shl_ln_fu_544_p3, "shl_ln_fu_544_p3");
    sc_trace(mVcdFile, r_V_15_fu_561_p1, "r_V_15_fu_561_p1");
    sc_trace(mVcdFile, r_V_15_fu_561_p2, "r_V_15_fu_561_p2");
    sc_trace(mVcdFile, tmp_9_fu_570_p4, "tmp_9_fu_570_p4");
    sc_trace(mVcdFile, rhs_V_1_fu_580_p3, "rhs_V_1_fu_580_p3");
    sc_trace(mVcdFile, lhs_V_fu_567_p1, "lhs_V_fu_567_p1");
    sc_trace(mVcdFile, sext_ln682_2_fu_588_p1, "sext_ln682_2_fu_588_p1");
    sc_trace(mVcdFile, ret_V_3_fu_592_p2, "ret_V_3_fu_592_p2");
    sc_trace(mVcdFile, f_Z4_V_fu_654_p4, "f_Z4_V_fu_654_p4");
    sc_trace(mVcdFile, rhs_V_2_fu_667_p1, "rhs_V_2_fu_667_p1");
    sc_trace(mVcdFile, lhs_V_1_fu_664_p1, "lhs_V_1_fu_664_p1");
    sc_trace(mVcdFile, ret_V_4_fu_671_p2, "ret_V_4_fu_671_p2");
    sc_trace(mVcdFile, r_V_16_fu_694_p0, "r_V_16_fu_694_p0");
    sc_trace(mVcdFile, r_V_16_fu_694_p1, "r_V_16_fu_694_p1");
    sc_trace(mVcdFile, r_V_16_fu_694_p2, "r_V_16_fu_694_p2");
    sc_trace(mVcdFile, tmp_s_fu_700_p4, "tmp_s_fu_700_p4");
    sc_trace(mVcdFile, zext_ln657_fu_710_p1, "zext_ln657_fu_710_p1");
    sc_trace(mVcdFile, ret_V_5_fu_724_p1, "ret_V_5_fu_724_p1");
    sc_trace(mVcdFile, zext_ln657_1_fu_727_p1, "zext_ln657_1_fu_727_p1");
    sc_trace(mVcdFile, tmp_1_fu_736_p4, "tmp_1_fu_736_p4");
    sc_trace(mVcdFile, lshr_ln662_6_fu_746_p4, "lshr_ln662_6_fu_746_p4");
    sc_trace(mVcdFile, exp_Z2P_m_1_V_fu_730_p2, "exp_Z2P_m_1_V_fu_730_p2");
    sc_trace(mVcdFile, r_V_17_fu_763_p0, "r_V_17_fu_763_p0");
    sc_trace(mVcdFile, r_V_17_fu_763_p1, "r_V_17_fu_763_p1");
    sc_trace(mVcdFile, r_V_17_fu_763_p2, "r_V_17_fu_763_p2");
    sc_trace(mVcdFile, lhs_V_2_fu_779_p5, "lhs_V_2_fu_779_p5");
    sc_trace(mVcdFile, tmp_2_fu_769_p4, "tmp_2_fu_769_p4");
    sc_trace(mVcdFile, zext_ln657_2_fu_794_p1, "zext_ln657_2_fu_794_p1");
    sc_trace(mVcdFile, add_ln657_2_fu_798_p2, "add_ln657_2_fu_798_p2");
    sc_trace(mVcdFile, zext_ln682_fu_790_p1, "zext_ln682_fu_790_p1");
    sc_trace(mVcdFile, zext_ln657_3_fu_804_p1, "zext_ln657_3_fu_804_p1");
    sc_trace(mVcdFile, exp_Z1P_m_1_l_V_fu_808_p2, "exp_Z1P_m_1_l_V_fu_808_p2");
    sc_trace(mVcdFile, lhs_V_3_fu_838_p1, "lhs_V_3_fu_838_p1");
    sc_trace(mVcdFile, r_V_18_fu_853_p0, "r_V_18_fu_853_p0");
    sc_trace(mVcdFile, r_V_18_fu_853_p1, "r_V_18_fu_853_p1");
    sc_trace(mVcdFile, ret_V_6_fu_841_p2, "ret_V_6_fu_841_p2");
    sc_trace(mVcdFile, r_V_18_fu_853_p2, "r_V_18_fu_853_p2");
    sc_trace(mVcdFile, trunc_ln1146_fu_875_p1, "trunc_ln1146_fu_875_p1");
    sc_trace(mVcdFile, zext_ln657_5_fu_867_p1, "zext_ln657_5_fu_867_p1");
    sc_trace(mVcdFile, lhs_V_4_fu_859_p3, "lhs_V_4_fu_859_p3");
    sc_trace(mVcdFile, trunc_ln_fu_879_p3, "trunc_ln_fu_879_p3");
    sc_trace(mVcdFile, zext_ln1146_fu_871_p1, "zext_ln1146_fu_871_p1");
    sc_trace(mVcdFile, add_ln1146_1_fu_893_p2, "add_ln1146_1_fu_893_p2");
    sc_trace(mVcdFile, tmp_7_fu_899_p3, "tmp_7_fu_899_p3");
    sc_trace(mVcdFile, r_exp_V_fu_907_p2, "r_exp_V_fu_907_p2");
    sc_trace(mVcdFile, r_exp_V_2_fu_912_p3, "r_exp_V_2_fu_912_p3");
    sc_trace(mVcdFile, tmp_8_fu_919_p4, "tmp_8_fu_919_p4");
    sc_trace(mVcdFile, icmp_ln849_fu_929_p2, "icmp_ln849_fu_929_p2");
    sc_trace(mVcdFile, tmp_10_fu_940_p3, "tmp_10_fu_940_p3");
    sc_trace(mVcdFile, ret_V_7_fu_887_p2, "ret_V_7_fu_887_p2");
    sc_trace(mVcdFile, tmp_fu_961_p4, "tmp_fu_961_p4");
    sc_trace(mVcdFile, tmp_6_fu_971_p4, "tmp_6_fu_971_p4");
    sc_trace(mVcdFile, trunc_ln168_fu_989_p1, "trunc_ln168_fu_989_p1");
    sc_trace(mVcdFile, out_exp_V_fu_993_p2, "out_exp_V_fu_993_p2");
    sc_trace(mVcdFile, tmp_V_4_fu_981_p3, "tmp_V_4_fu_981_p3");
    sc_trace(mVcdFile, p_Result_24_fu_999_p4, "p_Result_24_fu_999_p4");
    sc_trace(mVcdFile, or_ln338_fu_935_p2, "or_ln338_fu_935_p2");
    sc_trace(mVcdFile, xor_ln338_fu_1024_p2, "xor_ln338_fu_1024_p2");
    sc_trace(mVcdFile, and_ln338_fu_1019_p2, "and_ln338_fu_1019_p2");
    sc_trace(mVcdFile, and_ln849_fu_1029_p2, "and_ln849_fu_1029_p2");
    sc_trace(mVcdFile, or_ln849_fu_1035_p2, "or_ln849_fu_1035_p2");
    sc_trace(mVcdFile, xor_ln214_fu_1013_p2, "xor_ln214_fu_1013_p2");
    sc_trace(mVcdFile, sel_tmp5_fu_1041_p2, "sel_tmp5_fu_1041_p2");
    sc_trace(mVcdFile, select_ln339_fu_947_p3, "select_ln339_fu_947_p3");
    sc_trace(mVcdFile, bitcast_ln512_fu_1009_p1, "bitcast_ln512_fu_1009_p1");
    sc_trace(mVcdFile, xor_ln338_1_fu_1055_p2, "xor_ln338_1_fu_1055_p2");
    sc_trace(mVcdFile, or_ln849_1_fu_1066_p2, "or_ln849_1_fu_1066_p2");
    sc_trace(mVcdFile, and_ln338_1_fu_1061_p2, "and_ln338_1_fu_1061_p2");
    sc_trace(mVcdFile, xor_ln849_fu_1071_p2, "xor_ln849_fu_1071_p2");
    sc_trace(mVcdFile, or_ln849_2_fu_1077_p2, "or_ln849_2_fu_1077_p2");
    sc_trace(mVcdFile, tmp19_fu_1083_p2, "tmp19_fu_1083_p2");
    sc_trace(mVcdFile, icmp_ln853_fu_955_p2, "icmp_ln853_fu_955_p2");
    sc_trace(mVcdFile, xor_ln936_fu_1095_p2, "xor_ln936_fu_1095_p2");
    sc_trace(mVcdFile, x_is_pinf_fu_1100_p2, "x_is_pinf_fu_1100_p2");
    sc_trace(mVcdFile, or_ln214_fu_1105_p2, "or_ln214_fu_1105_p2");
    sc_trace(mVcdFile, select_ln214_fu_1110_p3, "select_ln214_fu_1110_p3");
    sc_trace(mVcdFile, select_ln214_1_fu_1117_p3, "select_ln214_1_fu_1117_p3");
    sc_trace(mVcdFile, select_ln214_2_fu_1125_p3, "select_ln214_2_fu_1125_p3");
    sc_trace(mVcdFile, grp_fu_1138_p0, "grp_fu_1138_p0");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0_0to5, "ap_idle_pp0_0to5");
    sc_trace(mVcdFile, ap_reset_idle_pp0, "ap_reset_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, r_V_16_fu_694_p00, "r_V_16_fu_694_p00");
    sc_trace(mVcdFile, r_V_16_fu_694_p10, "r_V_16_fu_694_p10");
    sc_trace(mVcdFile, r_V_17_fu_763_p00, "r_V_17_fu_763_p00");
    sc_trace(mVcdFile, r_V_17_fu_763_p10, "r_V_17_fu_763_p10");
    sc_trace(mVcdFile, r_V_18_fu_853_p00, "r_V_18_fu_853_p00");
    sc_trace(mVcdFile, r_V_18_fu_853_p10, "r_V_18_fu_853_p10");
#endif

    }
}

exp_generic_double_s::~exp_generic_double_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete table_exp_Z1_array_s_U;
    delete table_f_Z3_array_V_U;
    delete table_f_Z2_array_V_U;
    delete myip_v1_0_HLS_maceOg_U1;
}

void exp_generic_double_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_pp0_stage0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = ap_start.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter6 = ap_enable_reg_pp0_iter5.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        Z2_V_reg_1202 = ret_V_3_fu_592_p2.read().range(50, 43);
        Z3_V_reg_1209 = ret_V_3_fu_592_p2.read().range(42, 35);
        Z4_V_reg_1215 = Z4_V_fu_628_p1.read();
        Z4_ind_V_reg_1220 = ret_V_3_fu_592_p2.read().range(34, 27);
        and_ln18_reg_1161 = and_ln18_fu_311_p2.read();
        and_ln18_reg_1161_pp0_iter1_reg = and_ln18_reg_1161.read();
        and_ln209_reg_1154 = and_ln209_fu_299_p2.read();
        and_ln209_reg_1154_pp0_iter1_reg = and_ln209_reg_1154.read();
        icmp_ln338_1_reg_1192 = icmp_ln338_1_fu_552_p2.read();
        icmp_ln338_1_reg_1192_pp0_iter1_reg = icmp_ln338_1_reg_1192.read();
        icmp_ln338_reg_1184 = icmp_ln338_fu_530_p2.read();
        icmp_ln338_reg_1184_pp0_iter1_reg = icmp_ln338_reg_1184.read();
        m_diff_hi_V_reg_1197 = ret_V_3_fu_592_p2.read().range(58, 51);
        p_Result_22_reg_1149 = p_Val2_s_fu_261_p1.read().range(63, 63);
        p_Result_22_reg_1149_pp0_iter1_reg = p_Result_22_reg_1149.read();
        r_V_13_reg_1172 = r_V_13_fu_415_p3.read();
        r_exp_V_3_reg_1177 = r_exp_V_3_fu_522_p3.read();
        r_exp_V_3_reg_1177_pp0_iter1_reg = r_exp_V_3_reg_1177.read();
        select_ln253_reg_1167 = select_ln253_fu_341_p3.read();
        select_ln253_reg_1167_pp0_iter1_reg = select_ln253_reg_1167.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        Z2_V_reg_1202_pp0_iter2_reg = Z2_V_reg_1202.read();
        Z2_V_reg_1202_pp0_iter3_reg = Z2_V_reg_1202_pp0_iter2_reg.read();
        Z3_V_reg_1209_pp0_iter2_reg = Z3_V_reg_1209.read();
        Z4_V_reg_1215_pp0_iter2_reg = Z4_V_reg_1215.read();
        add_ln657_reg_1245 = add_ln657_fu_714_p2.read();
        and_ln18_reg_1161_pp0_iter2_reg = and_ln18_reg_1161_pp0_iter1_reg.read();
        and_ln18_reg_1161_pp0_iter3_reg = and_ln18_reg_1161_pp0_iter2_reg.read();
        and_ln18_reg_1161_pp0_iter4_reg = and_ln18_reg_1161_pp0_iter3_reg.read();
        and_ln18_reg_1161_pp0_iter5_reg = and_ln18_reg_1161_pp0_iter4_reg.read();
        and_ln209_reg_1154_pp0_iter2_reg = and_ln209_reg_1154_pp0_iter1_reg.read();
        and_ln209_reg_1154_pp0_iter3_reg = and_ln209_reg_1154_pp0_iter2_reg.read();
        and_ln209_reg_1154_pp0_iter4_reg = and_ln209_reg_1154_pp0_iter3_reg.read();
        and_ln209_reg_1154_pp0_iter5_reg = and_ln209_reg_1154_pp0_iter4_reg.read();
        exp_Z1P_m_1_V_reg_1260 = exp_Z1P_m_1_l_V_fu_808_p2.read().range(51, 2);
        exp_Z1_V_reg_1255 = table_exp_Z1_array_s_q0.read();
        exp_Z1_hi_V_reg_1265 = table_exp_Z1_array_s_q0.read().range(57, 8);
        icmp_ln338_1_reg_1192_pp0_iter2_reg = icmp_ln338_1_reg_1192_pp0_iter1_reg.read();
        icmp_ln338_1_reg_1192_pp0_iter3_reg = icmp_ln338_1_reg_1192_pp0_iter2_reg.read();
        icmp_ln338_1_reg_1192_pp0_iter4_reg = icmp_ln338_1_reg_1192_pp0_iter3_reg.read();
        icmp_ln338_reg_1184_pp0_iter2_reg = icmp_ln338_reg_1184_pp0_iter1_reg.read();
        icmp_ln338_reg_1184_pp0_iter3_reg = icmp_ln338_reg_1184_pp0_iter2_reg.read();
        icmp_ln338_reg_1184_pp0_iter4_reg = icmp_ln338_reg_1184_pp0_iter3_reg.read();
        m_diff_hi_V_reg_1197_pp0_iter2_reg = m_diff_hi_V_reg_1197.read();
        or_ln214_1_reg_1270 = or_ln214_1_fu_834_p2.read();
        p_Result_22_reg_1149_pp0_iter2_reg = p_Result_22_reg_1149_pp0_iter1_reg.read();
        p_Result_22_reg_1149_pp0_iter3_reg = p_Result_22_reg_1149_pp0_iter2_reg.read();
        p_Result_22_reg_1149_pp0_iter4_reg = p_Result_22_reg_1149_pp0_iter3_reg.read();
        p_Result_22_reg_1149_pp0_iter5_reg = p_Result_22_reg_1149_pp0_iter4_reg.read();
        r_exp_V_3_reg_1177_pp0_iter2_reg = r_exp_V_3_reg_1177_pp0_iter1_reg.read();
        r_exp_V_3_reg_1177_pp0_iter3_reg = r_exp_V_3_reg_1177_pp0_iter2_reg.read();
        r_exp_V_3_reg_1177_pp0_iter4_reg = r_exp_V_3_reg_1177_pp0_iter3_reg.read();
        sel_tmp16_reg_1280 = sel_tmp16_fu_1089_p2.read();
        sel_tmp6_reg_1275 = sel_tmp6_fu_1047_p3.read();
        select_ln253_reg_1167_pp0_iter2_reg = select_ln253_reg_1167_pp0_iter1_reg.read();
        select_ln253_reg_1167_pp0_iter3_reg = select_ln253_reg_1167_pp0_iter2_reg.read();
        select_ln253_reg_1167_pp0_iter4_reg = select_ln253_reg_1167_pp0_iter3_reg.read();
        tmp_i_reg_1240 = tmp_i_fu_677_p4.read();
    }
}

void exp_generic_double_s::thread_Z4_V_fu_628_p1() {
    Z4_V_fu_628_p1 = ret_V_3_fu_592_p2.read().range(35-1, 0);
}

void exp_generic_double_s::thread_add_ln1146_1_fu_893_p2() {
    add_ln1146_1_fu_893_p2 = (!trunc_ln_fu_879_p3.read().is_01() || !zext_ln1146_fu_871_p1.read().is_01())? sc_lv<107>(): (sc_biguint<107>(trunc_ln_fu_879_p3.read()) + sc_biguint<107>(zext_ln1146_fu_871_p1.read()));
}

void exp_generic_double_s::thread_add_ln657_2_fu_798_p2() {
    add_ln657_2_fu_798_p2 = (!zext_ln657_2_fu_794_p1.read().is_01() || !exp_Z2P_m_1_V_fu_730_p2.read().is_01())? sc_lv<44>(): (sc_biguint<44>(zext_ln657_2_fu_794_p1.read()) + sc_biguint<44>(exp_Z2P_m_1_V_fu_730_p2.read()));
}

void exp_generic_double_s::thread_add_ln657_fu_714_p2() {
    add_ln657_fu_714_p2 = (!zext_ln657_fu_710_p1.read().is_01() || !ret_V_4_fu_671_p2.read().is_01())? sc_lv<36>(): (sc_biguint<36>(zext_ln657_fu_710_p1.read()) + sc_biguint<36>(ret_V_4_fu_671_p2.read()));
}

void exp_generic_double_s::thread_add_ln805_fu_508_p2() {
    add_ln805_fu_508_p2 = (!ap_const_lv13_1.is_01() || !tmp_5_fu_483_p4.read().is_01())? sc_lv<13>(): (sc_biguint<13>(ap_const_lv13_1) + sc_biguint<13>(tmp_5_fu_483_p4.read()));
}

void exp_generic_double_s::thread_and_ln18_fu_311_p2() {
    and_ln18_fu_311_p2 = (icmp_ln833_fu_287_p2.read() & icmp_ln833_3_fu_305_p2.read());
}

void exp_generic_double_s::thread_and_ln209_fu_299_p2() {
    and_ln209_fu_299_p2 = (icmp_ln833_fu_287_p2.read() & icmp_ln837_fu_293_p2.read());
}

void exp_generic_double_s::thread_and_ln338_1_fu_1061_p2() {
    and_ln338_1_fu_1061_p2 = (icmp_ln338_reg_1184_pp0_iter4_reg.read() & xor_ln338_1_fu_1055_p2.read());
}

void exp_generic_double_s::thread_and_ln338_fu_1019_p2() {
    and_ln338_fu_1019_p2 = (icmp_ln338_reg_1184_pp0_iter4_reg.read() & or_ln338_fu_935_p2.read());
}

void exp_generic_double_s::thread_and_ln849_fu_1029_p2() {
    and_ln849_fu_1029_p2 = (icmp_ln849_fu_929_p2.read() & xor_ln338_fu_1024_p2.read());
}

void exp_generic_double_s::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[0];
}

void exp_generic_double_s::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void exp_generic_double_s::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()));
}

void exp_generic_double_s::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()));
}

void exp_generic_double_s::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read());
}

void exp_generic_double_s::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void exp_generic_double_s::thread_ap_block_state3_pp0_stage0_iter2() {
    ap_block_state3_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void exp_generic_double_s::thread_ap_block_state4_pp0_stage0_iter3() {
    ap_block_state4_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void exp_generic_double_s::thread_ap_block_state5_pp0_stage0_iter4() {
    ap_block_state5_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void exp_generic_double_s::thread_ap_block_state6_pp0_stage0_iter5() {
    ap_block_state6_pp0_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void exp_generic_double_s::thread_ap_block_state7_pp0_stage0_iter6() {
    ap_block_state7_pp0_stage0_iter6 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void exp_generic_double_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void exp_generic_double_s::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void exp_generic_double_s::thread_ap_enable_reg_pp0_iter0() {
    ap_enable_reg_pp0_iter0 = ap_start.read();
}

void exp_generic_double_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void exp_generic_double_s::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter6.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void exp_generic_double_s::thread_ap_idle_pp0_0to5() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()))) {
        ap_idle_pp0_0to5 = ap_const_logic_1;
    } else {
        ap_idle_pp0_0to5 = ap_const_logic_0;
    }
}

void exp_generic_double_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void exp_generic_double_s::thread_ap_reset_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0_0to5.read()))) {
        ap_reset_idle_pp0 = ap_const_logic_1;
    } else {
        ap_reset_idle_pp0 = ap_const_logic_0;
    }
}

void exp_generic_double_s::thread_ap_return() {
    ap_return = (!sel_tmp16_reg_1280.read()[0].is_01())? sc_lv<64>(): ((sel_tmp16_reg_1280.read()[0].to_bool())? ap_const_lv64_0: select_ln214_2_fu_1125_p3.read());
}

void exp_generic_double_s::thread_bitcast_ln512_fu_1009_p1() {
    bitcast_ln512_fu_1009_p1 = p_Result_24_fu_999_p4.read();
}

void exp_generic_double_s::thread_e_frac_V_fu_335_p2() {
    e_frac_V_fu_335_p2 = (!ap_const_lv54_0.is_01() || !p_Result_s_fu_327_p3.read().is_01())? sc_lv<54>(): (sc_biguint<54>(ap_const_lv54_0) - sc_biguint<54>(p_Result_s_fu_327_p3.read()));
}

void exp_generic_double_s::thread_exp_Z1P_m_1_l_V_fu_808_p2() {
    exp_Z1P_m_1_l_V_fu_808_p2 = (!zext_ln682_fu_790_p1.read().is_01() || !zext_ln657_3_fu_804_p1.read().is_01())? sc_lv<52>(): (sc_biguint<52>(zext_ln682_fu_790_p1.read()) + sc_biguint<52>(zext_ln657_3_fu_804_p1.read()));
}

void exp_generic_double_s::thread_exp_Z2P_m_1_V_fu_730_p2() {
    exp_Z2P_m_1_V_fu_730_p2 = (!ret_V_5_fu_724_p1.read().is_01() || !zext_ln657_1_fu_727_p1.read().is_01())? sc_lv<44>(): (sc_biguint<44>(ret_V_5_fu_724_p1.read()) + sc_biguint<44>(zext_ln657_1_fu_727_p1.read()));
}

void exp_generic_double_s::thread_f_Z4_V_fu_654_p4() {
    f_Z4_V_fu_654_p4 = table_f_Z3_array_V_q0.read().range(25, 16);
}

void exp_generic_double_s::thread_grp_fu_1138_p0() {
    grp_fu_1138_p0 =  (sc_lv<16>) (ap_const_lv31_5C55);
}

void exp_generic_double_s::thread_icmp_ln338_1_fu_552_p2() {
    icmp_ln338_1_fu_552_p2 = (!shl_ln_fu_544_p3.read().is_01() || !sext_ln682_fu_357_p1.read().is_01())? sc_lv<1>(): sc_lv<1>(shl_ln_fu_544_p3.read() != sext_ln682_fu_357_p1.read());
}

void exp_generic_double_s::thread_icmp_ln338_fu_530_p2() {
    icmp_ln338_fu_530_p2 = (!m_exp_fu_321_p2.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(m_exp_fu_321_p2.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void exp_generic_double_s::thread_icmp_ln805_fu_502_p2() {
    icmp_ln805_fu_502_p2 = (!trunc_ln805_fu_499_p1.read().is_01() || !ap_const_lv18_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln805_fu_499_p1.read() == ap_const_lv18_0);
}

void exp_generic_double_s::thread_icmp_ln833_3_fu_305_p2() {
    icmp_ln833_3_fu_305_p2 = (!tmp_V_3_fu_283_p1.read().is_01() || !ap_const_lv52_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_V_3_fu_283_p1.read() == ap_const_lv52_0);
}

void exp_generic_double_s::thread_icmp_ln833_fu_287_p2() {
    icmp_ln833_fu_287_p2 = (!tmp_V_fu_273_p4.read().is_01() || !ap_const_lv11_7FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_V_fu_273_p4.read() == ap_const_lv11_7FF);
}

void exp_generic_double_s::thread_icmp_ln837_fu_293_p2() {
    icmp_ln837_fu_293_p2 = (!tmp_V_3_fu_283_p1.read().is_01() || !ap_const_lv52_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_V_3_fu_283_p1.read() != ap_const_lv52_0);
}

void exp_generic_double_s::thread_icmp_ln849_fu_929_p2() {
    icmp_ln849_fu_929_p2 = (!tmp_8_fu_919_p4.read().is_01() || !ap_const_lv3_0.is_01())? sc_lv<1>(): (sc_bigint<3>(tmp_8_fu_919_p4.read()) > sc_bigint<3>(ap_const_lv3_0));
}

void exp_generic_double_s::thread_icmp_ln853_fu_955_p2() {
    icmp_ln853_fu_955_p2 = (!r_exp_V_2_fu_912_p3.read().is_01() || !ap_const_lv13_1C02.is_01())? sc_lv<1>(): (sc_bigint<13>(r_exp_V_2_fu_912_p3.read()) < sc_bigint<13>(ap_const_lv13_1C02));
}

void exp_generic_double_s::thread_isNeg_fu_361_p3() {
    isNeg_fu_361_p3 = m_exp_fu_321_p2.read().range(11, 11);
}

void exp_generic_double_s::thread_lhs_V_1_fu_664_p1() {
    lhs_V_1_fu_664_p1 = esl_zext<36,35>(Z4_V_reg_1215_pp0_iter2_reg.read());
}

void exp_generic_double_s::thread_lhs_V_2_fu_779_p5() {
    lhs_V_2_fu_779_p5 = esl_concat<49,2>(esl_concat<9,40>(esl_concat<8,1>(Z2_V_reg_1202_pp0_iter3_reg.read(), ap_const_lv1_0), tmp_1_fu_736_p4.read()), ap_const_lv2_0);
}

void exp_generic_double_s::thread_lhs_V_3_fu_838_p1() {
    lhs_V_3_fu_838_p1 = esl_zext<59,58>(exp_Z1_V_reg_1255.read());
}

void exp_generic_double_s::thread_lhs_V_4_fu_859_p3() {
    lhs_V_4_fu_859_p3 = esl_concat<59,49>(ret_V_6_fu_841_p2.read(), ap_const_lv49_0);
}

void exp_generic_double_s::thread_lhs_V_fu_567_p1() {
    lhs_V_fu_567_p1 = esl_sext<73,71>(r_V_13_reg_1172.read());
}

void exp_generic_double_s::thread_lshr_ln662_6_fu_746_p4() {
    lshr_ln662_6_fu_746_p4 = esl_concat<9,40>(esl_concat<8,1>(Z2_V_reg_1202_pp0_iter3_reg.read(), ap_const_lv1_0), tmp_1_fu_736_p4.read());
}

void exp_generic_double_s::thread_m_exp_2_fu_379_p3() {
    m_exp_2_fu_379_p3 = (!isNeg_fu_361_p3.read()[0].is_01())? sc_lv<12>(): ((isNeg_fu_361_p3.read()[0].to_bool())? sext_ln1311_fu_375_p1.read(): m_exp_fu_321_p2.read());
}

void exp_generic_double_s::thread_m_exp_fu_321_p2() {
    m_exp_fu_321_p2 = (!ap_const_lv12_C01.is_01() || !zext_ln502_fu_317_p1.read().is_01())? sc_lv<12>(): (sc_bigint<12>(ap_const_lv12_C01) + sc_biguint<12>(zext_ln502_fu_317_p1.read()));
}

void exp_generic_double_s::thread_m_fix_hi_V_fu_449_p4() {
    m_fix_hi_V_fu_449_p4 = r_V_13_fu_415_p3.read().range(70, 55);
}

void exp_generic_double_s::thread_m_fix_l_V_fu_423_p4() {
    m_fix_l_V_fu_423_p4 = r_V_13_fu_415_p3.read().range(70, 7);
}

void exp_generic_double_s::thread_m_frac_l_V_fu_349_p3() {
    m_frac_l_V_fu_349_p3 = esl_concat<54,7>(select_ln253_fu_341_p3.read(), ap_const_lv7_0);
}

void exp_generic_double_s::thread_or_ln214_1_fu_834_p2() {
    or_ln214_1_fu_834_p2 = (and_ln209_reg_1154_pp0_iter4_reg.read() | and_ln18_reg_1161_pp0_iter4_reg.read());
}

void exp_generic_double_s::thread_or_ln214_fu_1105_p2() {
    or_ln214_fu_1105_p2 = (and_ln209_reg_1154_pp0_iter5_reg.read() | x_is_pinf_fu_1100_p2.read());
}

void exp_generic_double_s::thread_or_ln338_fu_935_p2() {
    or_ln338_fu_935_p2 = (icmp_ln338_1_reg_1192_pp0_iter4_reg.read() | icmp_ln849_fu_929_p2.read());
}

void exp_generic_double_s::thread_or_ln849_1_fu_1066_p2() {
    or_ln849_1_fu_1066_p2 = (icmp_ln338_reg_1184_pp0_iter4_reg.read() | icmp_ln849_fu_929_p2.read());
}

void exp_generic_double_s::thread_or_ln849_2_fu_1077_p2() {
    or_ln849_2_fu_1077_p2 = (and_ln338_1_fu_1061_p2.read() | xor_ln849_fu_1071_p2.read());
}

void exp_generic_double_s::thread_or_ln849_fu_1035_p2() {
    or_ln849_fu_1035_p2 = (and_ln338_fu_1019_p2.read() | and_ln849_fu_1029_p2.read());
}

void exp_generic_double_s::thread_out_exp_V_fu_993_p2() {
    out_exp_V_fu_993_p2 = (!ap_const_lv11_3FF.is_01() || !trunc_ln168_fu_989_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_3FF) + sc_biguint<11>(trunc_ln168_fu_989_p1.read()));
}

void exp_generic_double_s::thread_p_Result_15_fu_492_p3() {
    p_Result_15_fu_492_p3 = grp_fu_1138_p3.read().range(30, 30);
}

void exp_generic_double_s::thread_p_Result_22_fu_265_p3() {
    p_Result_22_fu_265_p3 = p_Val2_s_fu_261_p1.read().range(63, 63);
}

void exp_generic_double_s::thread_p_Result_23_fu_459_p3() {
    p_Result_23_fu_459_p3 = r_V_13_fu_415_p3.read().range(70, 70);
}

void exp_generic_double_s::thread_p_Result_24_fu_999_p4() {
    p_Result_24_fu_999_p4 = esl_concat<12,52>(esl_concat<1,11>(ap_const_lv1_0, out_exp_V_fu_993_p2.read()), tmp_V_4_fu_981_p3.read());
}

void exp_generic_double_s::thread_p_Result_s_fu_327_p3() {
    p_Result_s_fu_327_p3 = esl_concat<2,52>(ap_const_lv2_1, tmp_V_3_fu_283_p1.read());
}

void exp_generic_double_s::thread_p_Val2_s_fu_261_p1() {
    p_Val2_s_fu_261_p1 = x.read();
}

void exp_generic_double_s::thread_r_V_13_fu_415_p3() {
    r_V_13_fu_415_p3 = (!isNeg_fu_361_p3.read()[0].is_01())? sc_lv<71>(): ((isNeg_fu_361_p3.read()[0].to_bool())? sext_ln1287_fu_405_p1.read(): r_V_1_fu_409_p2.read());
}

void exp_generic_double_s::thread_r_V_15_fu_561_p1() {
    r_V_15_fu_561_p1 = r_exp_V_3_reg_1177.read();
}

void exp_generic_double_s::thread_r_V_15_fu_561_p2() {
    r_V_15_fu_561_p2 = (!ap_const_lv84_58B90BFBE8E7BCD5E4.is_01() || !r_V_15_fu_561_p1.read().is_01())? sc_lv<84>(): sc_biguint<84>(ap_const_lv84_58B90BFBE8E7BCD5E4) * sc_bigint<13>(r_V_15_fu_561_p1.read());
}

void exp_generic_double_s::thread_r_V_16_fu_694_p0() {
    r_V_16_fu_694_p0 =  (sc_lv<36>) (r_V_16_fu_694_p00.read());
}

void exp_generic_double_s::thread_r_V_16_fu_694_p00() {
    r_V_16_fu_694_p00 = esl_zext<79,36>(ret_V_4_fu_671_p2.read());
}

void exp_generic_double_s::thread_r_V_16_fu_694_p1() {
    r_V_16_fu_694_p1 =  (sc_lv<43>) (r_V_16_fu_694_p10.read());
}

void exp_generic_double_s::thread_r_V_16_fu_694_p10() {
    r_V_16_fu_694_p10 = esl_zext<79,43>(tmp_i_fu_677_p4.read());
}

void exp_generic_double_s::thread_r_V_16_fu_694_p2() {
    r_V_16_fu_694_p2 = (!r_V_16_fu_694_p0.read().is_01() || !r_V_16_fu_694_p1.read().is_01())? sc_lv<79>(): sc_biguint<36>(r_V_16_fu_694_p0.read()) * sc_biguint<43>(r_V_16_fu_694_p1.read());
}

void exp_generic_double_s::thread_r_V_17_fu_763_p0() {
    r_V_17_fu_763_p0 =  (sc_lv<44>) (r_V_17_fu_763_p00.read());
}

void exp_generic_double_s::thread_r_V_17_fu_763_p00() {
    r_V_17_fu_763_p00 = esl_zext<93,44>(exp_Z2P_m_1_V_fu_730_p2.read());
}

void exp_generic_double_s::thread_r_V_17_fu_763_p1() {
    r_V_17_fu_763_p1 =  (sc_lv<49>) (r_V_17_fu_763_p10.read());
}

void exp_generic_double_s::thread_r_V_17_fu_763_p10() {
    r_V_17_fu_763_p10 = esl_zext<93,49>(lshr_ln662_6_fu_746_p4.read());
}

void exp_generic_double_s::thread_r_V_17_fu_763_p2() {
    r_V_17_fu_763_p2 = (!r_V_17_fu_763_p0.read().is_01() || !r_V_17_fu_763_p1.read().is_01())? sc_lv<93>(): sc_biguint<44>(r_V_17_fu_763_p0.read()) * sc_biguint<49>(r_V_17_fu_763_p1.read());
}

void exp_generic_double_s::thread_r_V_18_fu_853_p0() {
    r_V_18_fu_853_p0 =  (sc_lv<50>) (r_V_18_fu_853_p00.read());
}

void exp_generic_double_s::thread_r_V_18_fu_853_p00() {
    r_V_18_fu_853_p00 = esl_zext<100,50>(exp_Z1P_m_1_V_reg_1260.read());
}

void exp_generic_double_s::thread_r_V_18_fu_853_p1() {
    r_V_18_fu_853_p1 =  (sc_lv<50>) (r_V_18_fu_853_p10.read());
}

void exp_generic_double_s::thread_r_V_18_fu_853_p10() {
    r_V_18_fu_853_p10 = esl_zext<100,50>(exp_Z1_hi_V_reg_1265.read());
}

void exp_generic_double_s::thread_r_V_18_fu_853_p2() {
    r_V_18_fu_853_p2 = (!r_V_18_fu_853_p0.read().is_01() || !r_V_18_fu_853_p1.read().is_01())? sc_lv<100>(): sc_biguint<50>(r_V_18_fu_853_p0.read()) * sc_biguint<50>(r_V_18_fu_853_p1.read());
}

void exp_generic_double_s::thread_r_V_1_fu_409_p2() {
    r_V_1_fu_409_p2 = (!zext_ln1287_fu_391_p1.read().is_01())? sc_lv<71>(): sext_ln682_fu_357_p1.read() << (unsigned short)zext_ln1287_fu_391_p1.read().to_uint();
}

void exp_generic_double_s::thread_r_V_3_fu_437_p2() {
    r_V_3_fu_437_p2 = (!zext_ln1253_fu_433_p1.read().is_01())? sc_lv<64>(): m_fix_l_V_fu_423_p4.read() << (unsigned short)zext_ln1253_fu_433_p1.read().to_uint();
}

void exp_generic_double_s::thread_r_V_4_fu_443_p2() {
    r_V_4_fu_443_p2 = (!m_fix_l_V_fu_423_p4.read().is_01() || !zext_ln1253_fu_433_p1.read().is_01())? sc_lv<64>(): sc_bigint<64>(m_fix_l_V_fu_423_p4.read()) >> (unsigned short)zext_ln1253_fu_433_p1.read().to_uint();
}

void exp_generic_double_s::thread_r_V_fu_399_p2() {
    r_V_fu_399_p2 = (!m_frac_l_V_fu_349_p3.read().is_01() || !zext_ln1285_fu_395_p1.read().is_01())? sc_lv<61>(): sc_bigint<61>(m_frac_l_V_fu_349_p3.read()) >> (unsigned short)zext_ln1285_fu_395_p1.read().to_uint();
}

void exp_generic_double_s::thread_r_exp_V_2_fu_912_p3() {
    r_exp_V_2_fu_912_p3 = (!tmp_7_fu_899_p3.read()[0].is_01())? sc_lv<13>(): ((tmp_7_fu_899_p3.read()[0].to_bool())? r_exp_V_3_reg_1177_pp0_iter4_reg.read(): r_exp_V_fu_907_p2.read());
}

void exp_generic_double_s::thread_r_exp_V_3_fu_522_p3() {
    r_exp_V_3_fu_522_p3 = (!p_Result_15_fu_492_p3.read()[0].is_01())? sc_lv<13>(): ((p_Result_15_fu_492_p3.read()[0].to_bool())? select_ln805_fu_514_p3.read(): tmp_5_fu_483_p4.read());
}

void exp_generic_double_s::thread_r_exp_V_fu_907_p2() {
    r_exp_V_fu_907_p2 = (!ap_const_lv13_1FFF.is_01() || !r_exp_V_3_reg_1177_pp0_iter4_reg.read().is_01())? sc_lv<13>(): (sc_bigint<13>(ap_const_lv13_1FFF) + sc_bigint<13>(r_exp_V_3_reg_1177_pp0_iter4_reg.read()));
}

void exp_generic_double_s::thread_ret_V_3_fu_592_p2() {
    ret_V_3_fu_592_p2 = (!lhs_V_fu_567_p1.read().is_01() || !sext_ln682_2_fu_588_p1.read().is_01())? sc_lv<73>(): (sc_bigint<73>(lhs_V_fu_567_p1.read()) - sc_bigint<73>(sext_ln682_2_fu_588_p1.read()));
}

void exp_generic_double_s::thread_ret_V_4_fu_671_p2() {
    ret_V_4_fu_671_p2 = (!rhs_V_2_fu_667_p1.read().is_01() || !lhs_V_1_fu_664_p1.read().is_01())? sc_lv<36>(): (sc_biguint<36>(rhs_V_2_fu_667_p1.read()) + sc_biguint<36>(lhs_V_1_fu_664_p1.read()));
}

void exp_generic_double_s::thread_ret_V_5_fu_724_p1() {
    ret_V_5_fu_724_p1 = esl_zext<44,43>(tmp_i_reg_1240.read());
}

void exp_generic_double_s::thread_ret_V_6_fu_841_p2() {
    ret_V_6_fu_841_p2 = (!ap_const_lv59_10.is_01() || !lhs_V_3_fu_838_p1.read().is_01())? sc_lv<59>(): (sc_biguint<59>(ap_const_lv59_10) + sc_biguint<59>(lhs_V_3_fu_838_p1.read()));
}

void exp_generic_double_s::thread_ret_V_7_fu_887_p2() {
    ret_V_7_fu_887_p2 = (!zext_ln657_5_fu_867_p1.read().is_01() || !lhs_V_4_fu_859_p3.read().is_01())? sc_lv<108>(): (sc_biguint<108>(zext_ln657_5_fu_867_p1.read()) + sc_biguint<108>(lhs_V_4_fu_859_p3.read()));
}

void exp_generic_double_s::thread_rhs_V_1_fu_580_p3() {
    rhs_V_1_fu_580_p3 = esl_concat<71,1>(tmp_9_fu_570_p4.read(), ap_const_lv1_0);
}

void exp_generic_double_s::thread_rhs_V_2_fu_667_p1() {
    rhs_V_2_fu_667_p1 = esl_zext<36,10>(f_Z4_V_fu_654_p4.read());
}

void exp_generic_double_s::thread_rhs_V_fu_471_p3() {
    rhs_V_fu_471_p3 = esl_concat<1,18>(p_Result_23_fu_459_p3.read(), ap_const_lv18_20000);
}

void exp_generic_double_s::thread_sel_tmp16_fu_1089_p2() {
    sel_tmp16_fu_1089_p2 = (tmp19_fu_1083_p2.read() & icmp_ln853_fu_955_p2.read());
}

void exp_generic_double_s::thread_sel_tmp5_fu_1041_p2() {
    sel_tmp5_fu_1041_p2 = (or_ln849_fu_1035_p2.read() & xor_ln214_fu_1013_p2.read());
}

void exp_generic_double_s::thread_sel_tmp6_fu_1047_p3() {
    sel_tmp6_fu_1047_p3 = (!sel_tmp5_fu_1041_p2.read()[0].is_01())? sc_lv<64>(): ((sel_tmp5_fu_1041_p2.read()[0].to_bool())? select_ln339_fu_947_p3.read(): bitcast_ln512_fu_1009_p1.read());
}

void exp_generic_double_s::thread_select_ln1322_fu_536_p3() {
    select_ln1322_fu_536_p3 = (!isNeg_fu_361_p3.read()[0].is_01())? sc_lv<64>(): ((isNeg_fu_361_p3.read()[0].to_bool())? r_V_3_fu_437_p2.read(): r_V_4_fu_443_p2.read());
}

void exp_generic_double_s::thread_select_ln214_1_fu_1117_p3() {
    select_ln214_1_fu_1117_p3 = (!or_ln214_fu_1105_p2.read()[0].is_01())? sc_lv<64>(): ((or_ln214_fu_1105_p2.read()[0].to_bool())? select_ln214_fu_1110_p3.read(): ap_const_lv64_0);
}

void exp_generic_double_s::thread_select_ln214_2_fu_1125_p3() {
    select_ln214_2_fu_1125_p3 = (!or_ln214_1_reg_1270.read()[0].is_01())? sc_lv<64>(): ((or_ln214_1_reg_1270.read()[0].to_bool())? select_ln214_1_fu_1117_p3.read(): sel_tmp6_reg_1275.read());
}

void exp_generic_double_s::thread_select_ln214_fu_1110_p3() {
    select_ln214_fu_1110_p3 = (!and_ln209_reg_1154_pp0_iter5_reg.read()[0].is_01())? sc_lv<64>(): ((and_ln209_reg_1154_pp0_iter5_reg.read()[0].to_bool())? ap_const_lv64_7FFFFFFFFFFFFFFF: ap_const_lv64_7FF0000000000000);
}

void exp_generic_double_s::thread_select_ln253_fu_341_p3() {
    select_ln253_fu_341_p3 = (!p_Result_22_fu_265_p3.read()[0].is_01())? sc_lv<54>(): ((p_Result_22_fu_265_p3.read()[0].to_bool())? e_frac_V_fu_335_p2.read(): p_Result_s_fu_327_p3.read());
}

void exp_generic_double_s::thread_select_ln339_fu_947_p3() {
    select_ln339_fu_947_p3 = (!tmp_10_fu_940_p3.read()[0].is_01())? sc_lv<64>(): ((tmp_10_fu_940_p3.read()[0].to_bool())? ap_const_lv64_0: ap_const_lv64_7FF0000000000000);
}

void exp_generic_double_s::thread_select_ln805_fu_514_p3() {
    select_ln805_fu_514_p3 = (!icmp_ln805_fu_502_p2.read()[0].is_01())? sc_lv<13>(): ((icmp_ln805_fu_502_p2.read()[0].to_bool())? tmp_5_fu_483_p4.read(): add_ln805_fu_508_p2.read());
}

void exp_generic_double_s::thread_sext_ln1287_fu_405_p1() {
    sext_ln1287_fu_405_p1 = esl_sext<71,61>(r_V_fu_399_p2.read());
}

void exp_generic_double_s::thread_sext_ln1311_1_fu_387_p1() {
    sext_ln1311_1_fu_387_p1 = esl_sext<32,12>(m_exp_2_fu_379_p3.read());
}

void exp_generic_double_s::thread_sext_ln1311_fu_375_p1() {
    sext_ln1311_fu_375_p1 = esl_sext<12,11>(sub_ln1311_fu_369_p2.read());
}

void exp_generic_double_s::thread_sext_ln682_2_fu_588_p1() {
    sext_ln682_2_fu_588_p1 = esl_sext<73,72>(rhs_V_1_fu_580_p3.read());
}

void exp_generic_double_s::thread_sext_ln682_fu_357_p1() {
    sext_ln682_fu_357_p1 = esl_sext<71,61>(m_frac_l_V_fu_349_p3.read());
}

void exp_generic_double_s::thread_shl_ln_fu_544_p3() {
    shl_ln_fu_544_p3 = esl_concat<64,7>(select_ln1322_fu_536_p3.read(), ap_const_lv7_0);
}

void exp_generic_double_s::thread_sub_ln1311_fu_369_p2() {
    sub_ln1311_fu_369_p2 = (!ap_const_lv11_3FF.is_01() || !tmp_V_fu_273_p4.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_3FF) - sc_biguint<11>(tmp_V_fu_273_p4.read()));
}

void exp_generic_double_s::thread_table_exp_Z1_array_s_address0() {
    table_exp_Z1_array_s_address0 =  (sc_lv<8>) (zext_ln498_fu_650_p1.read());
}

void exp_generic_double_s::thread_table_exp_Z1_array_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        table_exp_Z1_array_s_ce0 = ap_const_logic_1;
    } else {
        table_exp_Z1_array_s_ce0 = ap_const_logic_0;
    }
}

void exp_generic_double_s::thread_table_f_Z2_array_V_address0() {
    table_f_Z2_array_V_address0 =  (sc_lv<8>) (zext_ln498_3_fu_720_p1.read());
}

void exp_generic_double_s::thread_table_f_Z2_array_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        table_f_Z2_array_V_ce0 = ap_const_logic_1;
    } else {
        table_f_Z2_array_V_ce0 = ap_const_logic_0;
    }
}

void exp_generic_double_s::thread_table_f_Z3_array_V_address0() {
    table_f_Z3_array_V_address0 =  (sc_lv<8>) (zext_ln498_1_fu_642_p1.read());
}

void exp_generic_double_s::thread_table_f_Z3_array_V_address1() {
    table_f_Z3_array_V_address1 =  (sc_lv<8>) (zext_ln498_2_fu_646_p1.read());
}

void exp_generic_double_s::thread_table_f_Z3_array_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        table_f_Z3_array_V_ce0 = ap_const_logic_1;
    } else {
        table_f_Z3_array_V_ce0 = ap_const_logic_0;
    }
}

void exp_generic_double_s::thread_table_f_Z3_array_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        table_f_Z3_array_V_ce1 = ap_const_logic_1;
    } else {
        table_f_Z3_array_V_ce1 = ap_const_logic_0;
    }
}

void exp_generic_double_s::thread_tmp19_fu_1083_p2() {
    tmp19_fu_1083_p2 = (or_ln849_2_fu_1077_p2.read() & xor_ln214_fu_1013_p2.read());
}

void exp_generic_double_s::thread_tmp_10_fu_940_p3() {
    tmp_10_fu_940_p3 = select_ln253_reg_1167_pp0_iter4_reg.read().range(53, 53);
}

void exp_generic_double_s::thread_tmp_1_fu_736_p4() {
    tmp_1_fu_736_p4 = table_f_Z2_array_V_q0.read().range(41, 2);
}

void exp_generic_double_s::thread_tmp_2_fu_769_p4() {
    tmp_2_fu_769_p4 = r_V_17_fu_763_p2.read().range(92, 57);
}

void exp_generic_double_s::thread_tmp_5_fu_483_p4() {
    tmp_5_fu_483_p4 = grp_fu_1138_p3.read().range(30, 18);
}

void exp_generic_double_s::thread_tmp_6_fu_971_p4() {
    tmp_6_fu_971_p4 = ret_V_7_fu_887_p2.read().range(104, 53);
}

void exp_generic_double_s::thread_tmp_7_fu_899_p3() {
    tmp_7_fu_899_p3 = add_ln1146_1_fu_893_p2.read().range(106, 106);
}

void exp_generic_double_s::thread_tmp_8_fu_919_p4() {
    tmp_8_fu_919_p4 = r_exp_V_2_fu_912_p3.read().range(12, 10);
}

void exp_generic_double_s::thread_tmp_9_fu_570_p4() {
    tmp_9_fu_570_p4 = r_V_15_fu_561_p2.read().range(83, 13);
}

void exp_generic_double_s::thread_tmp_V_3_fu_283_p1() {
    tmp_V_3_fu_283_p1 = p_Val2_s_fu_261_p1.read().range(52-1, 0);
}

void exp_generic_double_s::thread_tmp_V_4_fu_981_p3() {
    tmp_V_4_fu_981_p3 = (!tmp_7_fu_899_p3.read()[0].is_01())? sc_lv<52>(): ((tmp_7_fu_899_p3.read()[0].to_bool())? tmp_fu_961_p4.read(): tmp_6_fu_971_p4.read());
}

void exp_generic_double_s::thread_tmp_V_fu_273_p4() {
    tmp_V_fu_273_p4 = p_Val2_s_fu_261_p1.read().range(62, 52);
}

void exp_generic_double_s::thread_tmp_fu_961_p4() {
    tmp_fu_961_p4 = ret_V_7_fu_887_p2.read().range(105, 54);
}

void exp_generic_double_s::thread_tmp_i_fu_677_p4() {
    tmp_i_fu_677_p4 = esl_concat<17,26>(esl_concat<8,9>(Z3_V_reg_1209_pp0_iter2_reg.read(), ap_const_lv9_0), table_f_Z3_array_V_q1.read());
}

void exp_generic_double_s::thread_tmp_s_fu_700_p4() {
    tmp_s_fu_700_p4 = r_V_16_fu_694_p2.read().range(78, 59);
}

void exp_generic_double_s::thread_trunc_ln1146_fu_875_p1() {
    trunc_ln1146_fu_875_p1 = ret_V_6_fu_841_p2.read().range(58-1, 0);
}

void exp_generic_double_s::thread_trunc_ln168_fu_989_p1() {
    trunc_ln168_fu_989_p1 = r_exp_V_2_fu_912_p3.read().range(11-1, 0);
}

void exp_generic_double_s::thread_trunc_ln805_fu_499_p1() {
    trunc_ln805_fu_499_p1 = grp_fu_1138_p3.read().range(18-1, 0);
}

void exp_generic_double_s::thread_trunc_ln_fu_879_p3() {
    trunc_ln_fu_879_p3 = esl_concat<58,49>(trunc_ln1146_fu_875_p1.read(), ap_const_lv49_0);
}

void exp_generic_double_s::thread_x_is_pinf_fu_1100_p2() {
    x_is_pinf_fu_1100_p2 = (and_ln18_reg_1161_pp0_iter5_reg.read() & xor_ln936_fu_1095_p2.read());
}

void exp_generic_double_s::thread_xor_ln214_fu_1013_p2() {
    xor_ln214_fu_1013_p2 = (or_ln214_1_fu_834_p2.read() ^ ap_const_lv1_1);
}

void exp_generic_double_s::thread_xor_ln338_1_fu_1055_p2() {
    xor_ln338_1_fu_1055_p2 = (or_ln338_fu_935_p2.read() ^ ap_const_lv1_1);
}

void exp_generic_double_s::thread_xor_ln338_fu_1024_p2() {
    xor_ln338_fu_1024_p2 = (icmp_ln338_reg_1184_pp0_iter4_reg.read() ^ ap_const_lv1_1);
}

void exp_generic_double_s::thread_xor_ln849_fu_1071_p2() {
    xor_ln849_fu_1071_p2 = (or_ln849_1_fu_1066_p2.read() ^ ap_const_lv1_1);
}

void exp_generic_double_s::thread_xor_ln936_fu_1095_p2() {
    xor_ln936_fu_1095_p2 = (p_Result_22_reg_1149_pp0_iter5_reg.read() ^ ap_const_lv1_1);
}

void exp_generic_double_s::thread_zext_ln1146_fu_871_p1() {
    zext_ln1146_fu_871_p1 = esl_zext<107,100>(r_V_18_fu_853_p2.read());
}

void exp_generic_double_s::thread_zext_ln1253_fu_433_p1() {
    zext_ln1253_fu_433_p1 = esl_zext<64,32>(sext_ln1311_1_fu_387_p1.read());
}

void exp_generic_double_s::thread_zext_ln1285_fu_395_p1() {
    zext_ln1285_fu_395_p1 = esl_zext<61,32>(sext_ln1311_1_fu_387_p1.read());
}

void exp_generic_double_s::thread_zext_ln1287_fu_391_p1() {
    zext_ln1287_fu_391_p1 = esl_zext<71,32>(sext_ln1311_1_fu_387_p1.read());
}

void exp_generic_double_s::thread_zext_ln498_1_fu_642_p1() {
    zext_ln498_1_fu_642_p1 = esl_zext<64,8>(Z4_ind_V_reg_1220.read());
}

void exp_generic_double_s::thread_zext_ln498_2_fu_646_p1() {
    zext_ln498_2_fu_646_p1 = esl_zext<64,8>(Z3_V_reg_1209.read());
}

void exp_generic_double_s::thread_zext_ln498_3_fu_720_p1() {
    zext_ln498_3_fu_720_p1 = esl_zext<64,8>(Z2_V_reg_1202_pp0_iter2_reg.read());
}

void exp_generic_double_s::thread_zext_ln498_fu_650_p1() {
    zext_ln498_fu_650_p1 = esl_zext<64,8>(m_diff_hi_V_reg_1197_pp0_iter2_reg.read());
}

void exp_generic_double_s::thread_zext_ln502_fu_317_p1() {
    zext_ln502_fu_317_p1 = esl_zext<12,11>(tmp_V_fu_273_p4.read());
}

void exp_generic_double_s::thread_zext_ln657_1_fu_727_p1() {
    zext_ln657_1_fu_727_p1 = esl_zext<44,36>(add_ln657_reg_1245.read());
}

void exp_generic_double_s::thread_zext_ln657_2_fu_794_p1() {
    zext_ln657_2_fu_794_p1 = esl_zext<44,36>(tmp_2_fu_769_p4.read());
}

void exp_generic_double_s::thread_zext_ln657_3_fu_804_p1() {
    zext_ln657_3_fu_804_p1 = esl_zext<52,44>(add_ln657_2_fu_798_p2.read());
}

void exp_generic_double_s::thread_zext_ln657_5_fu_867_p1() {
    zext_ln657_5_fu_867_p1 = esl_zext<108,100>(r_V_18_fu_853_p2.read());
}

void exp_generic_double_s::thread_zext_ln657_fu_710_p1() {
    zext_ln657_fu_710_p1 = esl_zext<36,20>(tmp_s_fu_700_p4.read());
}

void exp_generic_double_s::thread_zext_ln682_fu_790_p1() {
    zext_ln682_fu_790_p1 = esl_zext<52,51>(lhs_V_2_fu_779_p5.read());
}

void exp_generic_double_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

