// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "generic_tanh_double_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic generic_tanh_double_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic generic_tanh_double_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state1 = "1";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state2 = "10";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state3 = "100";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state4 = "1000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state5 = "10000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state6 = "100000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state7 = "1000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state8 = "10000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state9 = "100000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state10 = "1000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state11 = "10000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state12 = "100000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state34 = "1000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state35 = "10000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state36 = "100000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state37 = "1000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state38 = "10000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state39 = "100000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state40 = "1000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state41 = "10000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state42 = "100000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state43 = "1000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state44 = "10000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state45 = "100000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state46 = "1000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state47 = "10000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state48 = "100000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state49 = "1000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state50 = "10000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state51 = "100000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state52 = "1000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state53 = "10000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state54 = "100000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state55 = "1000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state56 = "10000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state57 = "100000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state58 = "1000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state59 = "10000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state60 = "100000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state61 = "1000000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state62 = "10000000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state63 = "100000000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state64 = "1000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state65 = "10000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state66 = "100000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state67 = "1000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state68 = "10000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state69 = "100000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state70 = "1000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state71 = "10000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state72 = "100000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state73 = "1000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state74 = "10000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state75 = "100000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state76 = "1000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state77 = "10000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state78 = "100000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state79 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state80 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state81 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state82 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state83 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state84 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state85 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state86 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state87 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<88> generic_tanh_double_s::ap_ST_fsm_state88 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const bool generic_tanh_double_s::ap_const_boolean_1 = true;
const sc_lv<32> generic_tanh_double_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> generic_tanh_double_s::ap_const_lv32_11 = "10001";
const sc_lv<32> generic_tanh_double_s::ap_const_lv32_16 = "10110";
const sc_lv<32> generic_tanh_double_s::ap_const_lv32_31 = "110001";
const sc_lv<32> generic_tanh_double_s::ap_const_lv32_36 = "110110";
const sc_lv<32> generic_tanh_double_s::ap_const_lv32_51 = "1010001";
const sc_lv<32> generic_tanh_double_s::ap_const_lv32_2C = "101100";
const sc_lv<32> generic_tanh_double_s::ap_const_lv32_4C = "1001100";
const sc_lv<1> generic_tanh_double_s::ap_const_lv1_0 = "0";
const sc_lv<1> generic_tanh_double_s::ap_const_lv1_1 = "1";
const sc_lv<32> generic_tanh_double_s::ap_const_lv32_1 = "1";
const sc_lv<32> generic_tanh_double_s::ap_const_lv32_2 = "10";
const sc_lv<32> generic_tanh_double_s::ap_const_lv32_6 = "110";
const sc_lv<32> generic_tanh_double_s::ap_const_lv32_D = "1101";
const sc_lv<32> generic_tanh_double_s::ap_const_lv32_37 = "110111";
const sc_lv<32> generic_tanh_double_s::ap_const_lv32_56 = "1010110";
const sc_lv<32> generic_tanh_double_s::ap_const_lv32_7 = "111";
const sc_lv<32> generic_tanh_double_s::ap_const_lv32_57 = "1010111";
const sc_lv<32> generic_tanh_double_s::ap_const_lv32_4D = "1001101";
const sc_lv<32> generic_tanh_double_s::ap_const_lv32_32 = "110010";
const sc_lv<64> generic_tanh_double_s::ap_const_lv64_3FF0000000000000 = "11111111110000000000000000000000000000000000000000000000000000";
const sc_lv<64> generic_tanh_double_s::ap_const_lv64_BFF0000000000000 = "1011111111110000000000000000000000000000000000000000000000000000";
const sc_lv<64> generic_tanh_double_s::ap_const_lv64_4000000000000000 = "100000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> generic_tanh_double_s::ap_const_lv32_12 = "10010";
const sc_lv<32> generic_tanh_double_s::ap_const_lv32_2D = "101101";
const sc_lv<32> generic_tanh_double_s::ap_const_lv32_52 = "1010010";
const sc_lv<32> generic_tanh_double_s::ap_const_lv32_17 = "10111";
const sc_lv<64> generic_tanh_double_s::ap_const_lv64_4036000000000000 = "100000000110110000000000000000000000000000000000000000000000000";
const sc_lv<52> generic_tanh_double_s::ap_const_lv52_0 = "0000000000000000000000000000000000000000000000000000";
const sc_lv<11> generic_tanh_double_s::ap_const_lv11_0 = "00000000000";
const sc_lv<32> generic_tanh_double_s::ap_const_lv32_3F = "111111";
const sc_lv<32> generic_tanh_double_s::ap_const_lv32_34 = "110100";
const sc_lv<32> generic_tanh_double_s::ap_const_lv32_3E = "111110";
const sc_lv<11> generic_tanh_double_s::ap_const_lv11_7FF = "11111111111";
const sc_lv<11> generic_tanh_double_s::ap_const_lv11_3C8 = "1111001000";
const sc_lv<64> generic_tanh_double_s::ap_const_lv64_7FFFFFFFFFFFFFFF = "111111111111111111111111111111111111111111111111111111111111111";
const sc_lv<11> generic_tanh_double_s::ap_const_lv11_3FF = "1111111111";
const sc_lv<64> generic_tanh_double_s::ap_const_lv64_8000000000000000 = "1000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<11> generic_tanh_double_s::ap_const_lv11_3E4 = "1111100100";
const sc_lv<11> generic_tanh_double_s::ap_const_lv11_3E3 = "1111100011";
const sc_lv<2> generic_tanh_double_s::ap_const_lv2_0 = "00";
const sc_lv<2> generic_tanh_double_s::ap_const_lv2_1 = "1";
const sc_lv<5> generic_tanh_double_s::ap_const_lv5_4 = "100";
const sc_lv<64> generic_tanh_double_s::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";

generic_tanh_double_s::generic_tanh_double_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_exp_generic_double_s_fu_87 = new exp_generic_double_s("grp_exp_generic_double_s_fu_87");
    grp_exp_generic_double_s_fu_87->ap_clk(ap_clk);
    grp_exp_generic_double_s_fu_87->ap_rst(ap_rst);
    grp_exp_generic_double_s_fu_87->ap_start(grp_exp_generic_double_s_fu_87_ap_start);
    grp_exp_generic_double_s_fu_87->ap_done(grp_exp_generic_double_s_fu_87_ap_done);
    grp_exp_generic_double_s_fu_87->ap_idle(grp_exp_generic_double_s_fu_87_ap_idle);
    grp_exp_generic_double_s_fu_87->ap_ready(grp_exp_generic_double_s_fu_87_ap_ready);
    grp_exp_generic_double_s_fu_87->x(x_3_reg_382);
    grp_exp_generic_double_s_fu_87->ap_return(grp_exp_generic_double_s_fu_87_ap_return);
    myip_v1_0_HLS_dadfYi_U7 = new myip_v1_0_HLS_dadfYi<1,5,64,64,64>("myip_v1_0_HLS_dadfYi_U7");
    myip_v1_0_HLS_dadfYi_U7->clk(ap_clk);
    myip_v1_0_HLS_dadfYi_U7->reset(ap_rst);
    myip_v1_0_HLS_dadfYi_U7->din0(grp_fu_98_p0);
    myip_v1_0_HLS_dadfYi_U7->din1(grp_fu_98_p1);
    myip_v1_0_HLS_dadfYi_U7->opcode(grp_fu_98_opcode);
    myip_v1_0_HLS_dadfYi_U7->ce(ap_var_for_const0);
    myip_v1_0_HLS_dadfYi_U7->dout(grp_fu_98_p2);
    myip_v1_0_HLS_dmug8j_U8 = new myip_v1_0_HLS_dmug8j<1,5,64,64,64>("myip_v1_0_HLS_dmug8j_U8");
    myip_v1_0_HLS_dmug8j_U8->clk(ap_clk);
    myip_v1_0_HLS_dmug8j_U8->reset(ap_rst);
    myip_v1_0_HLS_dmug8j_U8->din0(abst_in_reg_343);
    myip_v1_0_HLS_dmug8j_U8->din1(reg_132);
    myip_v1_0_HLS_dmug8j_U8->ce(ap_var_for_const0);
    myip_v1_0_HLS_dmug8j_U8->dout(grp_fu_108_p2);
    myip_v1_0_HLS_ddihbi_U9 = new myip_v1_0_HLS_ddihbi<1,22,64,64,64>("myip_v1_0_HLS_ddihbi_U9");
    myip_v1_0_HLS_ddihbi_U9->clk(ap_clk);
    myip_v1_0_HLS_ddihbi_U9->reset(ap_rst);
    myip_v1_0_HLS_ddihbi_U9->din0(grp_fu_112_p0);
    myip_v1_0_HLS_ddihbi_U9->din1(reg_132);
    myip_v1_0_HLS_ddihbi_U9->ce(ap_var_for_const0);
    myip_v1_0_HLS_ddihbi_U9->dout(grp_fu_112_p2);
    myip_v1_0_HLS_dcmibs_U10 = new myip_v1_0_HLS_dcmibs<1,2,64,64,1>("myip_v1_0_HLS_dcmibs_U10");
    myip_v1_0_HLS_dcmibs_U10->clk(ap_clk);
    myip_v1_0_HLS_dcmibs_U10->reset(ap_rst);
    myip_v1_0_HLS_dcmibs_U10->din0(grp_fu_117_p0);
    myip_v1_0_HLS_dcmibs_U10->din1(ap_var_for_const1);
    myip_v1_0_HLS_dcmibs_U10->ce(ap_var_for_const0);
    myip_v1_0_HLS_dcmibs_U10->opcode(ap_var_for_const2);
    myip_v1_0_HLS_dcmibs_U10->dout(grp_fu_117_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_abst_in_fu_185_p1);
    sensitive << ( p_Result_8_fu_177_p3 );

    SC_METHOD(thread_and_ln75_fu_209_p2);
    sensitive << ( icmp_ln833_1_fu_203_p2 );
    sensitive << ( grp_fu_122_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state45);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state46);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state50);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state51);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state55);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state56);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state77);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state78);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state82);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state83);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state87);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state88);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_NS_fsm_state8);
    sensitive << ( ap_NS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state51 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_resultf_4_phi_fu_74_p10);
    sensitive << ( reg_132 );
    sensitive << ( icmp_ln833_reg_351 );
    sensitive << ( icmp_ln849_reg_355 );
    sensitive << ( and_ln75_reg_359 );
    sensitive << ( tmp_4_reg_368 );
    sensitive << ( icmp_ln849_1_reg_372 );
    sensitive << ( resultf_4_reg_70 );
    sensitive << ( ap_CS_fsm_state51 );

    SC_METHOD(thread_ap_predicate_op138_call_state8_state7);
    sensitive << ( p_Result_7_fu_249_p3 );
    sensitive << ( or_ln10_fu_274_p2 );
    sensitive << ( or_ln9_fu_286_p2 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state51 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state51 );
    sensitive << ( select_ln775_fu_306_p3 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_bitcast_ln112_1_fu_302_p1);
    sensitive << ( xor_ln112_fu_296_p2 );

    SC_METHOD(thread_bitcast_ln112_fu_292_p1);
    sensitive << ( ap_phi_mux_resultf_4_phi_fu_74_p10 );

    SC_METHOD(thread_bitcast_ln84_fu_233_p1);
    sensitive << ( xor_ln84_fu_228_p2 );

    SC_METHOD(thread_bitcast_ln95_1_fu_323_p1);
    sensitive << ( xor_ln95_fu_317_p2 );

    SC_METHOD(thread_bitcast_ln95_fu_313_p1);
    sensitive << ( expx_reg_58 );

    SC_METHOD(thread_grp_exp_generic_double_s_fu_87_ap_start);
    sensitive << ( grp_exp_generic_double_s_fu_87_ap_start_reg );

    SC_METHOD(thread_grp_fu_112_p0);
    sensitive << ( bitcast_ln95_1_fu_323_p1 );
    sensitive << ( ap_CS_fsm_state56 );
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_grp_fu_117_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_Result_8_fu_177_p3 );

    SC_METHOD(thread_grp_fu_122_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln833_fu_191_p2 );
    sensitive << ( icmp_ln849_fu_197_p2 );
    sensitive << ( tmp_V_1_fu_168_p1 );

    SC_METHOD(thread_grp_fu_127_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( p_Result_7_fu_249_p3 );
    sensitive << ( tmp_V_2_fu_257_p4 );

    SC_METHOD(thread_grp_fu_98_opcode);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln833_fu_191_p2 );
    sensitive << ( icmp_ln849_fu_197_p2 );
    sensitive << ( and_ln75_fu_209_p2 );
    sensitive << ( icmp_ln849_1_reg_372 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state46 );

    SC_METHOD(thread_grp_fu_98_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( abst_in_fu_185_p1 );
    sensitive << ( abst_in_reg_343 );
    sensitive << ( icmp_ln849_1_reg_372 );
    sensitive << ( bitcast_ln84_fu_233_p1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( grp_exp_generic_double_s_fu_87_ap_return );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( expx_reg_58 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state46 );

    SC_METHOD(thread_grp_fu_98_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( reg_140 );
    sensitive << ( abst_in_reg_343 );
    sensitive << ( icmp_ln849_1_reg_372 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state46 );

    SC_METHOD(thread_icmp_ln10_fu_268_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( p_Result_7_fu_249_p3 );
    sensitive << ( tmp_V_2_fu_257_p4 );

    SC_METHOD(thread_icmp_ln833_1_fu_203_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_V_fu_158_p4 );
    sensitive << ( icmp_ln833_fu_191_p2 );
    sensitive << ( icmp_ln849_fu_197_p2 );

    SC_METHOD(thread_icmp_ln833_fu_191_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_V_fu_158_p4 );

    SC_METHOD(thread_icmp_ln849_1_fu_223_p2);
    sensitive << ( tmp_V_reg_333 );
    sensitive << ( grp_fu_117_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_icmp_ln849_fu_197_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_V_fu_158_p4 );
    sensitive << ( icmp_ln833_fu_191_p2 );

    SC_METHOD(thread_icmp_ln9_fu_280_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( p_Result_7_fu_249_p3 );
    sensitive << ( tmp_V_2_fu_257_p4 );

    SC_METHOD(thread_or_ln10_fu_274_p2);
    sensitive << ( icmp_ln10_fu_268_p2 );
    sensitive << ( grp_fu_127_p2 );

    SC_METHOD(thread_or_ln9_fu_286_p2);
    sensitive << ( grp_fu_127_p2 );
    sensitive << ( icmp_ln9_fu_280_p2 );

    SC_METHOD(thread_p_Result_7_fu_249_p3);
    sensitive << ( p_Val2_1_fu_245_p1 );

    SC_METHOD(thread_p_Result_8_fu_177_p3);
    sensitive << ( trunc_ln368_fu_173_p1 );

    SC_METHOD(thread_p_Val2_1_fu_245_p1);
    sensitive << ( x_3_fu_238_p3 );

    SC_METHOD(thread_p_Val2_s_fu_146_p1);
    sensitive << ( t_in );

    SC_METHOD(thread_select_ln67_fu_215_p3);
    sensitive << ( grp_fu_122_p2 );

    SC_METHOD(thread_select_ln775_fu_306_p3);
    sensitive << ( p_Result_s_reg_328 );
    sensitive << ( ap_phi_mux_resultf_4_phi_fu_74_p10 );
    sensitive << ( bitcast_ln112_1_fu_302_p1 );

    SC_METHOD(thread_tmp_V_1_fu_168_p1);
    sensitive << ( p_Val2_s_fu_146_p1 );

    SC_METHOD(thread_tmp_V_2_fu_257_p4);
    sensitive << ( p_Val2_1_fu_245_p1 );

    SC_METHOD(thread_tmp_V_fu_158_p4);
    sensitive << ( p_Val2_s_fu_146_p1 );

    SC_METHOD(thread_trunc_ln368_fu_173_p1);
    sensitive << ( p_Val2_s_fu_146_p1 );

    SC_METHOD(thread_x_3_fu_238_p3);
    sensitive << ( grp_fu_98_p2 );
    sensitive << ( icmp_ln849_1_reg_372 );

    SC_METHOD(thread_xor_ln112_fu_296_p2);
    sensitive << ( bitcast_ln112_fu_292_p1 );

    SC_METHOD(thread_xor_ln84_fu_228_p2);
    sensitive << ( p_Result_8_reg_338 );

    SC_METHOD(thread_xor_ln95_fu_317_p2);
    sensitive << ( bitcast_ln95_fu_313_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln833_fu_191_p2 );
    sensitive << ( icmp_ln849_fu_197_p2 );
    sensitive << ( and_ln75_fu_209_p2 );
    sensitive << ( grp_fu_117_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln849_1_reg_372 );
    sensitive << ( p_Result_7_reg_389 );
    sensitive << ( or_ln10_reg_393 );
    sensitive << ( or_ln9_reg_397 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state19 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const2);

    ap_CS_fsm = "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    grp_exp_generic_double_s_fu_87_ap_start_reg = SC_LOGIC_0;
    ap_return_preg = "0000000000000000000000000000000000000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "generic_tanh_double_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, t_in, "(port)t_in");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, grp_fu_98_p2, "grp_fu_98_p2");
    sc_trace(mVcdFile, reg_132, "reg_132");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, ap_CS_fsm_state50, "ap_CS_fsm_state50");
    sc_trace(mVcdFile, ap_CS_fsm_state55, "ap_CS_fsm_state55");
    sc_trace(mVcdFile, ap_CS_fsm_state82, "ap_CS_fsm_state82");
    sc_trace(mVcdFile, grp_fu_112_p2, "grp_fu_112_p2");
    sc_trace(mVcdFile, reg_140, "reg_140");
    sc_trace(mVcdFile, ap_CS_fsm_state45, "ap_CS_fsm_state45");
    sc_trace(mVcdFile, ap_CS_fsm_state77, "ap_CS_fsm_state77");
    sc_trace(mVcdFile, p_Result_s_reg_328, "p_Result_s_reg_328");
    sc_trace(mVcdFile, tmp_V_fu_158_p4, "tmp_V_fu_158_p4");
    sc_trace(mVcdFile, tmp_V_reg_333, "tmp_V_reg_333");
    sc_trace(mVcdFile, p_Result_8_fu_177_p3, "p_Result_8_fu_177_p3");
    sc_trace(mVcdFile, p_Result_8_reg_338, "p_Result_8_reg_338");
    sc_trace(mVcdFile, abst_in_fu_185_p1, "abst_in_fu_185_p1");
    sc_trace(mVcdFile, abst_in_reg_343, "abst_in_reg_343");
    sc_trace(mVcdFile, icmp_ln833_fu_191_p2, "icmp_ln833_fu_191_p2");
    sc_trace(mVcdFile, icmp_ln833_reg_351, "icmp_ln833_reg_351");
    sc_trace(mVcdFile, icmp_ln849_fu_197_p2, "icmp_ln849_fu_197_p2");
    sc_trace(mVcdFile, icmp_ln849_reg_355, "icmp_ln849_reg_355");
    sc_trace(mVcdFile, and_ln75_fu_209_p2, "and_ln75_fu_209_p2");
    sc_trace(mVcdFile, and_ln75_reg_359, "and_ln75_reg_359");
    sc_trace(mVcdFile, select_ln67_fu_215_p3, "select_ln67_fu_215_p3");
    sc_trace(mVcdFile, grp_fu_117_p2, "grp_fu_117_p2");
    sc_trace(mVcdFile, tmp_4_reg_368, "tmp_4_reg_368");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln849_1_fu_223_p2, "icmp_ln849_1_fu_223_p2");
    sc_trace(mVcdFile, icmp_ln849_1_reg_372, "icmp_ln849_1_reg_372");
    sc_trace(mVcdFile, bitcast_ln84_fu_233_p1, "bitcast_ln84_fu_233_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, x_3_fu_238_p3, "x_3_fu_238_p3");
    sc_trace(mVcdFile, x_3_reg_382, "x_3_reg_382");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, p_Result_7_fu_249_p3, "p_Result_7_fu_249_p3");
    sc_trace(mVcdFile, p_Result_7_reg_389, "p_Result_7_reg_389");
    sc_trace(mVcdFile, or_ln10_fu_274_p2, "or_ln10_fu_274_p2");
    sc_trace(mVcdFile, or_ln10_reg_393, "or_ln10_reg_393");
    sc_trace(mVcdFile, or_ln9_fu_286_p2, "or_ln9_fu_286_p2");
    sc_trace(mVcdFile, or_ln9_reg_397, "or_ln9_reg_397");
    sc_trace(mVcdFile, grp_exp_generic_double_s_fu_87_ap_return, "grp_exp_generic_double_s_fu_87_ap_return");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, bitcast_ln95_1_fu_323_p1, "bitcast_ln95_1_fu_323_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state56, "ap_CS_fsm_state56");
    sc_trace(mVcdFile, grp_fu_108_p2, "grp_fu_108_p2");
    sc_trace(mVcdFile, resultf_reg_411, "resultf_reg_411");
    sc_trace(mVcdFile, ap_CS_fsm_state87, "ap_CS_fsm_state87");
    sc_trace(mVcdFile, grp_exp_generic_double_s_fu_87_ap_start, "grp_exp_generic_double_s_fu_87_ap_start");
    sc_trace(mVcdFile, grp_exp_generic_double_s_fu_87_ap_done, "grp_exp_generic_double_s_fu_87_ap_done");
    sc_trace(mVcdFile, grp_exp_generic_double_s_fu_87_ap_idle, "grp_exp_generic_double_s_fu_87_ap_idle");
    sc_trace(mVcdFile, grp_exp_generic_double_s_fu_87_ap_ready, "grp_exp_generic_double_s_fu_87_ap_ready");
    sc_trace(mVcdFile, expx_reg_58, "expx_reg_58");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_phi_mux_resultf_4_phi_fu_74_p10, "ap_phi_mux_resultf_4_phi_fu_74_p10");
    sc_trace(mVcdFile, resultf_4_reg_70, "resultf_4_reg_70");
    sc_trace(mVcdFile, ap_CS_fsm_state88, "ap_CS_fsm_state88");
    sc_trace(mVcdFile, ap_CS_fsm_state78, "ap_CS_fsm_state78");
    sc_trace(mVcdFile, ap_CS_fsm_state51, "ap_CS_fsm_state51");
    sc_trace(mVcdFile, grp_exp_generic_double_s_fu_87_ap_start_reg, "grp_exp_generic_double_s_fu_87_ap_start_reg");
    sc_trace(mVcdFile, ap_predicate_op138_call_state8_state7, "ap_predicate_op138_call_state8_state7");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_NS_fsm_state8, "ap_NS_fsm_state8");
    sc_trace(mVcdFile, grp_fu_98_p0, "grp_fu_98_p0");
    sc_trace(mVcdFile, grp_fu_98_p1, "grp_fu_98_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, ap_CS_fsm_state46, "ap_CS_fsm_state46");
    sc_trace(mVcdFile, ap_CS_fsm_state83, "ap_CS_fsm_state83");
    sc_trace(mVcdFile, grp_fu_112_p0, "grp_fu_112_p0");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, grp_fu_117_p0, "grp_fu_117_p0");
    sc_trace(mVcdFile, tmp_V_1_fu_168_p1, "tmp_V_1_fu_168_p1");
    sc_trace(mVcdFile, tmp_V_2_fu_257_p4, "tmp_V_2_fu_257_p4");
    sc_trace(mVcdFile, p_Val2_s_fu_146_p1, "p_Val2_s_fu_146_p1");
    sc_trace(mVcdFile, trunc_ln368_fu_173_p1, "trunc_ln368_fu_173_p1");
    sc_trace(mVcdFile, icmp_ln833_1_fu_203_p2, "icmp_ln833_1_fu_203_p2");
    sc_trace(mVcdFile, grp_fu_122_p2, "grp_fu_122_p2");
    sc_trace(mVcdFile, xor_ln84_fu_228_p2, "xor_ln84_fu_228_p2");
    sc_trace(mVcdFile, p_Val2_1_fu_245_p1, "p_Val2_1_fu_245_p1");
    sc_trace(mVcdFile, icmp_ln10_fu_268_p2, "icmp_ln10_fu_268_p2");
    sc_trace(mVcdFile, grp_fu_127_p2, "grp_fu_127_p2");
    sc_trace(mVcdFile, icmp_ln9_fu_280_p2, "icmp_ln9_fu_280_p2");
    sc_trace(mVcdFile, bitcast_ln112_fu_292_p1, "bitcast_ln112_fu_292_p1");
    sc_trace(mVcdFile, xor_ln112_fu_296_p2, "xor_ln112_fu_296_p2");
    sc_trace(mVcdFile, bitcast_ln112_1_fu_302_p1, "bitcast_ln112_1_fu_302_p1");
    sc_trace(mVcdFile, bitcast_ln95_fu_313_p1, "bitcast_ln95_fu_313_p1");
    sc_trace(mVcdFile, xor_ln95_fu_317_p2, "xor_ln95_fu_317_p2");
    sc_trace(mVcdFile, grp_fu_98_opcode, "grp_fu_98_opcode");
    sc_trace(mVcdFile, select_ln775_fu_306_p3, "select_ln775_fu_306_p3");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
#endif

    }
}

generic_tanh_double_s::~generic_tanh_double_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_exp_generic_double_s_fu_87;
    delete myip_v1_0_HLS_dadfYi_U7;
    delete myip_v1_0_HLS_dmug8j_U8;
    delete myip_v1_0_HLS_ddihbi_U9;
    delete myip_v1_0_HLS_dcmibs_U10;
}

void generic_tanh_double_s::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void generic_tanh_double_s::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv64_4036000000000000;
}

void generic_tanh_double_s::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv5_4;
}

void generic_tanh_double_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv64_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state51.read())) {
            ap_return_preg = select_ln775_fu_306_p3.read();
        }
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, p_Result_7_reg_389.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_ln9_reg_397.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, p_Result_7_reg_389.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_ln10_reg_393.read())))) {
        expx_reg_58 = x_3_reg_382.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        expx_reg_58 = grp_fu_98_p2.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_exp_generic_double_s_fu_87_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
             esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op138_call_state8_state7.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_NS_fsm_state8.read()))) {
            grp_exp_generic_double_s_fu_87_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_exp_generic_double_s_fu_87_ap_ready.read())) {
            grp_exp_generic_double_s_fu_87_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(icmp_ln833_fu_191_p2.read(), ap_const_lv1_1))) {
        resultf_4_reg_70 = select_ln67_fu_215_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, grp_fu_117_p2.read()))) {
        resultf_4_reg_70 = ap_const_lv64_3FF0000000000000;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state51.read()) && 
                esl_seteq<1,1,1>(icmp_ln833_reg_351.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(icmp_ln849_reg_355.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, and_ln75_reg_359.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_4_reg_368.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln849_1_reg_372.read()))) {
        resultf_4_reg_70 = reg_132.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state78.read())) {
        resultf_4_reg_70 = reg_140.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state88.read())) {
        resultf_4_reg_70 = resultf_reg_411.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        abst_in_reg_343 = abst_in_fu_185_p1.read();
        icmp_ln833_reg_351 = icmp_ln833_fu_191_p2.read();
        p_Result_8_reg_338 = p_Result_8_fu_177_p3.read();
        p_Result_s_reg_328 = p_Val2_s_fu_146_p1.read().range(63, 63);
        tmp_V_reg_333 = p_Val2_s_fu_146_p1.read().range(62, 52);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(icmp_ln833_fu_191_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(icmp_ln849_fu_197_p2.read(), ap_const_lv1_0))) {
        and_ln75_reg_359 = and_ln75_fu_209_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, grp_fu_117_p2.read()))) {
        icmp_ln849_1_reg_372 = icmp_ln849_1_fu_223_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(icmp_ln833_fu_191_p2.read(), ap_const_lv1_0))) {
        icmp_ln849_reg_355 = icmp_ln849_fu_197_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, p_Result_7_fu_249_p3.read()))) {
        or_ln10_reg_393 = or_ln10_fu_274_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, p_Result_7_fu_249_p3.read()))) {
        or_ln9_reg_397 = or_ln9_fu_286_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        p_Result_7_reg_389 = p_Val2_1_fu_245_p1.read().range(63, 63);
        x_3_reg_382 = x_3_fu_238_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state50.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state55.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state82.read()))) {
        reg_132 = grp_fu_98_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state45.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state77.read()))) {
        reg_140 = grp_fu_112_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state87.read())) {
        resultf_reg_411 = grp_fu_108_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        tmp_4_reg_368 = grp_fu_117_p2.read();
    }
}

void generic_tanh_double_s::thread_abst_in_fu_185_p1() {
    abst_in_fu_185_p1 = p_Result_8_fu_177_p3.read();
}

void generic_tanh_double_s::thread_and_ln75_fu_209_p2() {
    and_ln75_fu_209_p2 = (icmp_ln833_1_fu_203_p2.read() & grp_fu_122_p2.read());
}

void generic_tanh_double_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void generic_tanh_double_s::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void generic_tanh_double_s::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void generic_tanh_double_s::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void generic_tanh_double_s::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void generic_tanh_double_s::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read()[22];
}

void generic_tanh_double_s::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read()[23];
}

void generic_tanh_double_s::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void generic_tanh_double_s::thread_ap_CS_fsm_state45() {
    ap_CS_fsm_state45 = ap_CS_fsm.read()[44];
}

void generic_tanh_double_s::thread_ap_CS_fsm_state46() {
    ap_CS_fsm_state46 = ap_CS_fsm.read()[45];
}

void generic_tanh_double_s::thread_ap_CS_fsm_state50() {
    ap_CS_fsm_state50 = ap_CS_fsm.read()[49];
}

void generic_tanh_double_s::thread_ap_CS_fsm_state51() {
    ap_CS_fsm_state51 = ap_CS_fsm.read()[50];
}

void generic_tanh_double_s::thread_ap_CS_fsm_state55() {
    ap_CS_fsm_state55 = ap_CS_fsm.read()[54];
}

void generic_tanh_double_s::thread_ap_CS_fsm_state56() {
    ap_CS_fsm_state56 = ap_CS_fsm.read()[55];
}

void generic_tanh_double_s::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void generic_tanh_double_s::thread_ap_CS_fsm_state77() {
    ap_CS_fsm_state77 = ap_CS_fsm.read()[76];
}

void generic_tanh_double_s::thread_ap_CS_fsm_state78() {
    ap_CS_fsm_state78 = ap_CS_fsm.read()[77];
}

void generic_tanh_double_s::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void generic_tanh_double_s::thread_ap_CS_fsm_state82() {
    ap_CS_fsm_state82 = ap_CS_fsm.read()[81];
}

void generic_tanh_double_s::thread_ap_CS_fsm_state83() {
    ap_CS_fsm_state83 = ap_CS_fsm.read()[82];
}

void generic_tanh_double_s::thread_ap_CS_fsm_state87() {
    ap_CS_fsm_state87 = ap_CS_fsm.read()[86];
}

void generic_tanh_double_s::thread_ap_CS_fsm_state88() {
    ap_CS_fsm_state88 = ap_CS_fsm.read()[87];
}

void generic_tanh_double_s::thread_ap_NS_fsm_state8() {
    ap_NS_fsm_state8 = ap_NS_fsm.read()[7];
}

void generic_tanh_double_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state51.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void generic_tanh_double_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void generic_tanh_double_s::thread_ap_phi_mux_resultf_4_phi_fu_74_p10() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state51.read()) && 
         esl_seteq<1,1,1>(icmp_ln833_reg_351.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(icmp_ln849_reg_355.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, and_ln75_reg_359.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_4_reg_368.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln849_1_reg_372.read()))) {
        ap_phi_mux_resultf_4_phi_fu_74_p10 = reg_132.read();
    } else {
        ap_phi_mux_resultf_4_phi_fu_74_p10 = resultf_4_reg_70.read();
    }
}

void generic_tanh_double_s::thread_ap_predicate_op138_call_state8_state7() {
    ap_predicate_op138_call_state8_state7 = ((esl_seteq<1,1,1>(ap_const_lv1_1, p_Result_7_fu_249_p3.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, or_ln9_fu_286_p2.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, p_Result_7_fu_249_p3.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, or_ln10_fu_274_p2.read())));
}

void generic_tanh_double_s::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state51.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void generic_tanh_double_s::thread_ap_return() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state51.read())) {
        ap_return = select_ln775_fu_306_p3.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void generic_tanh_double_s::thread_bitcast_ln112_1_fu_302_p1() {
    bitcast_ln112_1_fu_302_p1 = xor_ln112_fu_296_p2.read();
}

void generic_tanh_double_s::thread_bitcast_ln112_fu_292_p1() {
    bitcast_ln112_fu_292_p1 = ap_phi_mux_resultf_4_phi_fu_74_p10.read();
}

void generic_tanh_double_s::thread_bitcast_ln84_fu_233_p1() {
    bitcast_ln84_fu_233_p1 = xor_ln84_fu_228_p2.read();
}

void generic_tanh_double_s::thread_bitcast_ln95_1_fu_323_p1() {
    bitcast_ln95_1_fu_323_p1 = xor_ln95_fu_317_p2.read();
}

void generic_tanh_double_s::thread_bitcast_ln95_fu_313_p1() {
    bitcast_ln95_fu_313_p1 = expx_reg_58.read();
}

void generic_tanh_double_s::thread_grp_exp_generic_double_s_fu_87_ap_start() {
    grp_exp_generic_double_s_fu_87_ap_start = grp_exp_generic_double_s_fu_87_ap_start_reg.read();
}

void generic_tanh_double_s::thread_grp_fu_112_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state56.read())) {
        grp_fu_112_p0 = bitcast_ln95_1_fu_323_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        grp_fu_112_p0 = ap_const_lv64_4000000000000000;
    } else {
        grp_fu_112_p0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void generic_tanh_double_s::thread_grp_fu_117_p0() {
    grp_fu_117_p0 = p_Result_8_fu_177_p3.read();
}

void generic_tanh_double_s::thread_grp_fu_122_p2() {
    grp_fu_122_p2 = (!tmp_V_1_fu_168_p1.read().is_01() || !ap_const_lv52_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_V_1_fu_168_p1.read() == ap_const_lv52_0);
}

void generic_tanh_double_s::thread_grp_fu_127_p2() {
    grp_fu_127_p2 = (!tmp_V_2_fu_257_p4.read().is_01() || !ap_const_lv11_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_V_2_fu_257_p4.read() == ap_const_lv11_0);
}

void generic_tanh_double_s::thread_grp_fu_98_opcode() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln849_1_reg_372.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state46.read()))) {
        grp_fu_98_opcode = ap_const_lv2_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln849_1_reg_372.read())) || 
                (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln849_1_reg_372.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) || 
                (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln849_1_reg_372.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                 esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                 ((esl_seteq<1,1,1>(icmp_ln833_fu_191_p2.read(), ap_const_lv1_0) && 
                   esl_seteq<1,1,1>(and_ln75_fu_209_p2.read(), ap_const_lv1_1)) || 
                  (esl_seteq<1,1,1>(icmp_ln833_fu_191_p2.read(), ap_const_lv1_0) && 
                   esl_seteq<1,1,1>(icmp_ln849_fu_197_p2.read(), ap_const_lv1_1)))))) {
        grp_fu_98_opcode = ap_const_lv2_0;
    } else {
        grp_fu_98_opcode =  (sc_lv<2>) ("XX");
    }
}

void generic_tanh_double_s::thread_grp_fu_98_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state46.read())) {
        grp_fu_98_p0 = ap_const_lv64_3FF0000000000000;
    } else if (((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln849_1_reg_372.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) || 
                (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln849_1_reg_372.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())))) {
        grp_fu_98_p0 = expx_reg_58.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        grp_fu_98_p0 = grp_exp_generic_double_s_fu_87_ap_return.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln849_1_reg_372.read()))) {
        grp_fu_98_p0 = abst_in_reg_343.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln849_1_reg_372.read()))) {
        grp_fu_98_p0 = bitcast_ln84_fu_233_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        grp_fu_98_p0 = abst_in_fu_185_p1.read();
    } else {
        grp_fu_98_p0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void generic_tanh_double_s::thread_grp_fu_98_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state46.read())) {
        grp_fu_98_p1 = reg_140.read();
    } else if (((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln849_1_reg_372.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) || 
                (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln849_1_reg_372.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())))) {
        grp_fu_98_p1 = ap_const_lv64_4000000000000000;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        grp_fu_98_p1 = ap_const_lv64_BFF0000000000000;
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln849_1_reg_372.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln849_1_reg_372.read())))) {
        grp_fu_98_p1 = abst_in_reg_343.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        grp_fu_98_p1 = ap_const_lv64_3FF0000000000000;
    } else {
        grp_fu_98_p1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void generic_tanh_double_s::thread_icmp_ln10_fu_268_p2() {
    icmp_ln10_fu_268_p2 = (!tmp_V_2_fu_257_p4.read().is_01() || !ap_const_lv11_3E4.is_01())? sc_lv<1>(): (sc_biguint<11>(tmp_V_2_fu_257_p4.read()) > sc_biguint<11>(ap_const_lv11_3E4));
}

void generic_tanh_double_s::thread_icmp_ln833_1_fu_203_p2() {
    icmp_ln833_1_fu_203_p2 = (!tmp_V_fu_158_p4.read().is_01() || !ap_const_lv11_3C8.is_01())? sc_lv<1>(): sc_lv<1>(tmp_V_fu_158_p4.read() == ap_const_lv11_3C8);
}

void generic_tanh_double_s::thread_icmp_ln833_fu_191_p2() {
    icmp_ln833_fu_191_p2 = (!tmp_V_fu_158_p4.read().is_01() || !ap_const_lv11_7FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_V_fu_158_p4.read() == ap_const_lv11_7FF);
}

void generic_tanh_double_s::thread_icmp_ln849_1_fu_223_p2() {
    icmp_ln849_1_fu_223_p2 = (!tmp_V_reg_333.read().is_01() || !ap_const_lv11_3FF.is_01())? sc_lv<1>(): (sc_biguint<11>(tmp_V_reg_333.read()) < sc_biguint<11>(ap_const_lv11_3FF));
}

void generic_tanh_double_s::thread_icmp_ln849_fu_197_p2() {
    icmp_ln849_fu_197_p2 = (!tmp_V_fu_158_p4.read().is_01() || !ap_const_lv11_3C8.is_01())? sc_lv<1>(): (sc_biguint<11>(tmp_V_fu_158_p4.read()) < sc_biguint<11>(ap_const_lv11_3C8));
}

void generic_tanh_double_s::thread_icmp_ln9_fu_280_p2() {
    icmp_ln9_fu_280_p2 = (!tmp_V_2_fu_257_p4.read().is_01() || !ap_const_lv11_3E3.is_01())? sc_lv<1>(): (sc_biguint<11>(tmp_V_2_fu_257_p4.read()) > sc_biguint<11>(ap_const_lv11_3E3));
}

void generic_tanh_double_s::thread_or_ln10_fu_274_p2() {
    or_ln10_fu_274_p2 = (icmp_ln10_fu_268_p2.read() | grp_fu_127_p2.read());
}

void generic_tanh_double_s::thread_or_ln9_fu_286_p2() {
    or_ln9_fu_286_p2 = (icmp_ln9_fu_280_p2.read() | grp_fu_127_p2.read());
}

void generic_tanh_double_s::thread_p_Result_7_fu_249_p3() {
    p_Result_7_fu_249_p3 = p_Val2_1_fu_245_p1.read().range(63, 63);
}

void generic_tanh_double_s::thread_p_Result_8_fu_177_p3() {
    p_Result_8_fu_177_p3 = esl_concat<1,63>(ap_const_lv1_0, trunc_ln368_fu_173_p1.read());
}

void generic_tanh_double_s::thread_p_Val2_1_fu_245_p1() {
    p_Val2_1_fu_245_p1 = x_3_fu_238_p3.read();
}

void generic_tanh_double_s::thread_p_Val2_s_fu_146_p1() {
    p_Val2_s_fu_146_p1 = t_in.read();
}

void generic_tanh_double_s::thread_select_ln67_fu_215_p3() {
    select_ln67_fu_215_p3 = (!grp_fu_122_p2.read()[0].is_01())? sc_lv<64>(): ((grp_fu_122_p2.read()[0].to_bool())? ap_const_lv64_3FF0000000000000: ap_const_lv64_7FFFFFFFFFFFFFFF);
}

void generic_tanh_double_s::thread_select_ln775_fu_306_p3() {
    select_ln775_fu_306_p3 = (!p_Result_s_reg_328.read()[0].is_01())? sc_lv<64>(): ((p_Result_s_reg_328.read()[0].to_bool())? bitcast_ln112_1_fu_302_p1.read(): ap_phi_mux_resultf_4_phi_fu_74_p10.read());
}

void generic_tanh_double_s::thread_tmp_V_1_fu_168_p1() {
    tmp_V_1_fu_168_p1 = p_Val2_s_fu_146_p1.read().range(52-1, 0);
}

void generic_tanh_double_s::thread_tmp_V_2_fu_257_p4() {
    tmp_V_2_fu_257_p4 = p_Val2_1_fu_245_p1.read().range(62, 52);
}

void generic_tanh_double_s::thread_tmp_V_fu_158_p4() {
    tmp_V_fu_158_p4 = p_Val2_s_fu_146_p1.read().range(62, 52);
}

void generic_tanh_double_s::thread_trunc_ln368_fu_173_p1() {
    trunc_ln368_fu_173_p1 = p_Val2_s_fu_146_p1.read().range(63-1, 0);
}

void generic_tanh_double_s::thread_x_3_fu_238_p3() {
    x_3_fu_238_p3 = (!icmp_ln849_1_reg_372.read()[0].is_01())? sc_lv<64>(): ((icmp_ln849_1_reg_372.read()[0].to_bool())? grp_fu_98_p2.read(): grp_fu_98_p2.read());
}

void generic_tanh_double_s::thread_xor_ln112_fu_296_p2() {
    xor_ln112_fu_296_p2 = (bitcast_ln112_fu_292_p1.read() ^ ap_const_lv64_8000000000000000);
}

void generic_tanh_double_s::thread_xor_ln84_fu_228_p2() {
    xor_ln84_fu_228_p2 = (p_Result_8_reg_338.read() ^ ap_const_lv64_8000000000000000);
}

void generic_tanh_double_s::thread_xor_ln95_fu_317_p2() {
    xor_ln95_fu_317_p2 = (bitcast_ln95_fu_313_p1.read() ^ ap_const_lv64_8000000000000000);
}

void generic_tanh_double_s::thread_ap_NS_fsm() {
    if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state1))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(icmp_ln833_fu_191_p2.read(), ap_const_lv1_1))) {
            ap_NS_fsm = ap_ST_fsm_state51;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(icmp_ln833_fu_191_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(icmp_ln849_fu_197_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, and_ln75_fu_209_p2.read()))) {
            ap_NS_fsm = ap_ST_fsm_state2;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && ((esl_seteq<1,1,1>(icmp_ln833_fu_191_p2.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(and_ln75_fu_209_p2.read(), ap_const_lv1_1)) || 
  (esl_seteq<1,1,1>(icmp_ln833_fu_191_p2.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(icmp_ln849_fu_197_p2.read(), ap_const_lv1_1))))) {
            ap_NS_fsm = ap_ST_fsm_state79;
        } else {
            ap_NS_fsm = ap_ST_fsm_state1;
        }
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state2))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, grp_fu_117_p2.read()))) {
            ap_NS_fsm = ap_ST_fsm_state51;
        } else {
            ap_NS_fsm = ap_ST_fsm_state3;
        }
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state3))
    {
        ap_NS_fsm = ap_ST_fsm_state4;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state4))
    {
        ap_NS_fsm = ap_ST_fsm_state5;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state5))
    {
        ap_NS_fsm = ap_ST_fsm_state6;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state6))
    {
        ap_NS_fsm = ap_ST_fsm_state7;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state7))
    {
        ap_NS_fsm = ap_ST_fsm_state8;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state8))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && ((esl_seteq<1,1,1>(ap_const_lv1_1, p_Result_7_reg_389.read()) && 
   esl_seteq<1,1,1>(ap_const_lv1_0, or_ln9_reg_397.read())) || 
  (esl_seteq<1,1,1>(ap_const_lv1_0, p_Result_7_reg_389.read()) && 
   esl_seteq<1,1,1>(ap_const_lv1_0, or_ln10_reg_393.read()))))) {
            ap_NS_fsm = ap_ST_fsm_state19;
        } else {
            ap_NS_fsm = ap_ST_fsm_state9;
        }
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state9))
    {
        ap_NS_fsm = ap_ST_fsm_state10;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state10))
    {
        ap_NS_fsm = ap_ST_fsm_state11;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state11))
    {
        ap_NS_fsm = ap_ST_fsm_state12;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state12))
    {
        ap_NS_fsm = ap_ST_fsm_state13;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state13))
    {
        ap_NS_fsm = ap_ST_fsm_state14;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state14))
    {
        ap_NS_fsm = ap_ST_fsm_state15;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state15))
    {
        ap_NS_fsm = ap_ST_fsm_state16;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state16))
    {
        ap_NS_fsm = ap_ST_fsm_state17;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state17))
    {
        ap_NS_fsm = ap_ST_fsm_state18;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state18))
    {
        ap_NS_fsm = ap_ST_fsm_state19;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state19))
    {
        if ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln849_1_reg_372.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()))) {
            ap_NS_fsm = ap_ST_fsm_state52;
        } else {
            ap_NS_fsm = ap_ST_fsm_state20;
        }
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state20))
    {
        ap_NS_fsm = ap_ST_fsm_state21;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state21))
    {
        ap_NS_fsm = ap_ST_fsm_state22;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state22))
    {
        ap_NS_fsm = ap_ST_fsm_state23;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state23))
    {
        ap_NS_fsm = ap_ST_fsm_state24;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state24))
    {
        ap_NS_fsm = ap_ST_fsm_state25;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state25))
    {
        ap_NS_fsm = ap_ST_fsm_state26;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state26))
    {
        ap_NS_fsm = ap_ST_fsm_state27;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state27))
    {
        ap_NS_fsm = ap_ST_fsm_state28;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state28))
    {
        ap_NS_fsm = ap_ST_fsm_state29;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state29))
    {
        ap_NS_fsm = ap_ST_fsm_state30;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state30))
    {
        ap_NS_fsm = ap_ST_fsm_state31;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state31))
    {
        ap_NS_fsm = ap_ST_fsm_state32;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state32))
    {
        ap_NS_fsm = ap_ST_fsm_state33;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state33))
    {
        ap_NS_fsm = ap_ST_fsm_state34;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state34))
    {
        ap_NS_fsm = ap_ST_fsm_state35;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state35))
    {
        ap_NS_fsm = ap_ST_fsm_state36;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state36))
    {
        ap_NS_fsm = ap_ST_fsm_state37;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state37))
    {
        ap_NS_fsm = ap_ST_fsm_state38;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state38))
    {
        ap_NS_fsm = ap_ST_fsm_state39;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state39))
    {
        ap_NS_fsm = ap_ST_fsm_state40;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state40))
    {
        ap_NS_fsm = ap_ST_fsm_state41;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state41))
    {
        ap_NS_fsm = ap_ST_fsm_state42;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state42))
    {
        ap_NS_fsm = ap_ST_fsm_state43;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state43))
    {
        ap_NS_fsm = ap_ST_fsm_state44;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state44))
    {
        ap_NS_fsm = ap_ST_fsm_state45;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state45))
    {
        ap_NS_fsm = ap_ST_fsm_state46;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state46))
    {
        ap_NS_fsm = ap_ST_fsm_state47;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state47))
    {
        ap_NS_fsm = ap_ST_fsm_state48;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state48))
    {
        ap_NS_fsm = ap_ST_fsm_state49;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state49))
    {
        ap_NS_fsm = ap_ST_fsm_state50;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state50))
    {
        ap_NS_fsm = ap_ST_fsm_state51;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state51))
    {
        ap_NS_fsm = ap_ST_fsm_state1;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state52))
    {
        ap_NS_fsm = ap_ST_fsm_state53;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state53))
    {
        ap_NS_fsm = ap_ST_fsm_state54;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state54))
    {
        ap_NS_fsm = ap_ST_fsm_state55;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state55))
    {
        ap_NS_fsm = ap_ST_fsm_state56;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state56))
    {
        ap_NS_fsm = ap_ST_fsm_state57;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state57))
    {
        ap_NS_fsm = ap_ST_fsm_state58;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state58))
    {
        ap_NS_fsm = ap_ST_fsm_state59;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state59))
    {
        ap_NS_fsm = ap_ST_fsm_state60;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state60))
    {
        ap_NS_fsm = ap_ST_fsm_state61;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state61))
    {
        ap_NS_fsm = ap_ST_fsm_state62;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state62))
    {
        ap_NS_fsm = ap_ST_fsm_state63;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state63))
    {
        ap_NS_fsm = ap_ST_fsm_state64;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state64))
    {
        ap_NS_fsm = ap_ST_fsm_state65;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state65))
    {
        ap_NS_fsm = ap_ST_fsm_state66;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state66))
    {
        ap_NS_fsm = ap_ST_fsm_state67;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state67))
    {
        ap_NS_fsm = ap_ST_fsm_state68;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state68))
    {
        ap_NS_fsm = ap_ST_fsm_state69;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state69))
    {
        ap_NS_fsm = ap_ST_fsm_state70;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state70))
    {
        ap_NS_fsm = ap_ST_fsm_state71;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state71))
    {
        ap_NS_fsm = ap_ST_fsm_state72;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state72))
    {
        ap_NS_fsm = ap_ST_fsm_state73;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state73))
    {
        ap_NS_fsm = ap_ST_fsm_state74;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state74))
    {
        ap_NS_fsm = ap_ST_fsm_state75;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state75))
    {
        ap_NS_fsm = ap_ST_fsm_state76;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state76))
    {
        ap_NS_fsm = ap_ST_fsm_state77;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state77))
    {
        ap_NS_fsm = ap_ST_fsm_state78;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state78))
    {
        ap_NS_fsm = ap_ST_fsm_state51;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state79))
    {
        ap_NS_fsm = ap_ST_fsm_state80;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state80))
    {
        ap_NS_fsm = ap_ST_fsm_state81;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state81))
    {
        ap_NS_fsm = ap_ST_fsm_state82;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state82))
    {
        ap_NS_fsm = ap_ST_fsm_state83;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state83))
    {
        ap_NS_fsm = ap_ST_fsm_state84;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state84))
    {
        ap_NS_fsm = ap_ST_fsm_state85;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state85))
    {
        ap_NS_fsm = ap_ST_fsm_state86;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state86))
    {
        ap_NS_fsm = ap_ST_fsm_state87;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state87))
    {
        ap_NS_fsm = ap_ST_fsm_state88;
    }
    else if (esl_seteq<1,88,88>(ap_CS_fsm.read(), ap_ST_fsm_state88))
    {
        ap_NS_fsm = ap_ST_fsm_state51;
    }
    else
    {
        ap_NS_fsm =  (sc_lv<88>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}
}

