// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _generic_tanh_double_s_HH_
#define _generic_tanh_double_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "exp_generic_double_s.h"
#include "myip_v1_0_HLS_dadfYi.h"
#include "myip_v1_0_HLS_dmug8j.h"
#include "myip_v1_0_HLS_ddihbi.h"
#include "myip_v1_0_HLS_dcmibs.h"

namespace ap_rtl {

struct generic_tanh_double_s : public sc_module {
    // Port declarations 8
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<64> > t_in;
    sc_out< sc_lv<64> > ap_return;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<64> > ap_var_for_const1;
    sc_signal< sc_lv<5> > ap_var_for_const2;


    // Module declarations
    generic_tanh_double_s(sc_module_name name);
    SC_HAS_PROCESS(generic_tanh_double_s);

    ~generic_tanh_double_s();

    sc_trace_file* mVcdFile;

    exp_generic_double_s* grp_exp_generic_double_s_fu_87;
    myip_v1_0_HLS_dadfYi<1,5,64,64,64>* myip_v1_0_HLS_dadfYi_U7;
    myip_v1_0_HLS_dmug8j<1,5,64,64,64>* myip_v1_0_HLS_dmug8j_U8;
    myip_v1_0_HLS_ddihbi<1,22,64,64,64>* myip_v1_0_HLS_ddihbi_U9;
    myip_v1_0_HLS_dcmibs<1,2,64,64,1>* myip_v1_0_HLS_dcmibs_U10;
    sc_signal< sc_lv<88> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<64> > grp_fu_98_p2;
    sc_signal< sc_lv<64> > reg_132;
    sc_signal< sc_logic > ap_CS_fsm_state18;
    sc_signal< sc_logic > ap_CS_fsm_state23;
    sc_signal< sc_logic > ap_CS_fsm_state50;
    sc_signal< sc_logic > ap_CS_fsm_state55;
    sc_signal< sc_logic > ap_CS_fsm_state82;
    sc_signal< sc_lv<64> > grp_fu_112_p2;
    sc_signal< sc_lv<64> > reg_140;
    sc_signal< sc_logic > ap_CS_fsm_state45;
    sc_signal< sc_logic > ap_CS_fsm_state77;
    sc_signal< sc_lv<1> > p_Result_s_reg_328;
    sc_signal< sc_lv<11> > tmp_V_fu_158_p4;
    sc_signal< sc_lv<11> > tmp_V_reg_333;
    sc_signal< sc_lv<64> > p_Result_8_fu_177_p3;
    sc_signal< sc_lv<64> > p_Result_8_reg_338;
    sc_signal< sc_lv<64> > abst_in_fu_185_p1;
    sc_signal< sc_lv<64> > abst_in_reg_343;
    sc_signal< sc_lv<1> > icmp_ln833_fu_191_p2;
    sc_signal< sc_lv<1> > icmp_ln833_reg_351;
    sc_signal< sc_lv<1> > icmp_ln849_fu_197_p2;
    sc_signal< sc_lv<1> > icmp_ln849_reg_355;
    sc_signal< sc_lv<1> > and_ln75_fu_209_p2;
    sc_signal< sc_lv<1> > and_ln75_reg_359;
    sc_signal< sc_lv<64> > select_ln67_fu_215_p3;
    sc_signal< sc_lv<1> > grp_fu_117_p2;
    sc_signal< sc_lv<1> > tmp_4_reg_368;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > icmp_ln849_1_fu_223_p2;
    sc_signal< sc_lv<1> > icmp_ln849_1_reg_372;
    sc_signal< sc_lv<64> > bitcast_ln84_fu_233_p1;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<64> > x_3_fu_238_p3;
    sc_signal< sc_lv<64> > x_3_reg_382;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<1> > p_Result_7_fu_249_p3;
    sc_signal< sc_lv<1> > p_Result_7_reg_389;
    sc_signal< sc_lv<1> > or_ln10_fu_274_p2;
    sc_signal< sc_lv<1> > or_ln10_reg_393;
    sc_signal< sc_lv<1> > or_ln9_fu_286_p2;
    sc_signal< sc_lv<1> > or_ln9_reg_397;
    sc_signal< sc_lv<64> > grp_exp_generic_double_s_fu_87_ap_return;
    sc_signal< sc_logic > ap_CS_fsm_state14;
    sc_signal< sc_lv<64> > bitcast_ln95_1_fu_323_p1;
    sc_signal< sc_logic > ap_CS_fsm_state56;
    sc_signal< sc_lv<64> > grp_fu_108_p2;
    sc_signal< sc_lv<64> > resultf_reg_411;
    sc_signal< sc_logic > ap_CS_fsm_state87;
    sc_signal< sc_logic > grp_exp_generic_double_s_fu_87_ap_start;
    sc_signal< sc_logic > grp_exp_generic_double_s_fu_87_ap_done;
    sc_signal< sc_logic > grp_exp_generic_double_s_fu_87_ap_idle;
    sc_signal< sc_logic > grp_exp_generic_double_s_fu_87_ap_ready;
    sc_signal< sc_lv<64> > expx_reg_58;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<64> > ap_phi_mux_resultf_4_phi_fu_74_p10;
    sc_signal< sc_lv<64> > resultf_4_reg_70;
    sc_signal< sc_logic > ap_CS_fsm_state88;
    sc_signal< sc_logic > ap_CS_fsm_state78;
    sc_signal< sc_logic > ap_CS_fsm_state51;
    sc_signal< sc_logic > grp_exp_generic_double_s_fu_87_ap_start_reg;
    sc_signal< bool > ap_predicate_op138_call_state8_state7;
    sc_signal< sc_lv<88> > ap_NS_fsm;
    sc_signal< sc_logic > ap_NS_fsm_state8;
    sc_signal< sc_lv<64> > grp_fu_98_p0;
    sc_signal< sc_lv<64> > grp_fu_98_p1;
    sc_signal< sc_logic > ap_CS_fsm_state19;
    sc_signal< sc_logic > ap_CS_fsm_state46;
    sc_signal< sc_logic > ap_CS_fsm_state83;
    sc_signal< sc_lv<64> > grp_fu_112_p0;
    sc_signal< sc_logic > ap_CS_fsm_state24;
    sc_signal< sc_lv<64> > grp_fu_117_p0;
    sc_signal< sc_lv<52> > tmp_V_1_fu_168_p1;
    sc_signal< sc_lv<11> > tmp_V_2_fu_257_p4;
    sc_signal< sc_lv<64> > p_Val2_s_fu_146_p1;
    sc_signal< sc_lv<63> > trunc_ln368_fu_173_p1;
    sc_signal< sc_lv<1> > icmp_ln833_1_fu_203_p2;
    sc_signal< sc_lv<1> > grp_fu_122_p2;
    sc_signal< sc_lv<64> > xor_ln84_fu_228_p2;
    sc_signal< sc_lv<64> > p_Val2_1_fu_245_p1;
    sc_signal< sc_lv<1> > icmp_ln10_fu_268_p2;
    sc_signal< sc_lv<1> > grp_fu_127_p2;
    sc_signal< sc_lv<1> > icmp_ln9_fu_280_p2;
    sc_signal< sc_lv<64> > bitcast_ln112_fu_292_p1;
    sc_signal< sc_lv<64> > xor_ln112_fu_296_p2;
    sc_signal< sc_lv<64> > bitcast_ln112_1_fu_302_p1;
    sc_signal< sc_lv<64> > bitcast_ln95_fu_313_p1;
    sc_signal< sc_lv<64> > xor_ln95_fu_317_p2;
    sc_signal< sc_lv<2> > grp_fu_98_opcode;
    sc_signal< sc_lv<64> > select_ln775_fu_306_p3;
    sc_signal< sc_lv<64> > ap_return_preg;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<88> ap_ST_fsm_state1;
    static const sc_lv<88> ap_ST_fsm_state2;
    static const sc_lv<88> ap_ST_fsm_state3;
    static const sc_lv<88> ap_ST_fsm_state4;
    static const sc_lv<88> ap_ST_fsm_state5;
    static const sc_lv<88> ap_ST_fsm_state6;
    static const sc_lv<88> ap_ST_fsm_state7;
    static const sc_lv<88> ap_ST_fsm_state8;
    static const sc_lv<88> ap_ST_fsm_state9;
    static const sc_lv<88> ap_ST_fsm_state10;
    static const sc_lv<88> ap_ST_fsm_state11;
    static const sc_lv<88> ap_ST_fsm_state12;
    static const sc_lv<88> ap_ST_fsm_state13;
    static const sc_lv<88> ap_ST_fsm_state14;
    static const sc_lv<88> ap_ST_fsm_state15;
    static const sc_lv<88> ap_ST_fsm_state16;
    static const sc_lv<88> ap_ST_fsm_state17;
    static const sc_lv<88> ap_ST_fsm_state18;
    static const sc_lv<88> ap_ST_fsm_state19;
    static const sc_lv<88> ap_ST_fsm_state20;
    static const sc_lv<88> ap_ST_fsm_state21;
    static const sc_lv<88> ap_ST_fsm_state22;
    static const sc_lv<88> ap_ST_fsm_state23;
    static const sc_lv<88> ap_ST_fsm_state24;
    static const sc_lv<88> ap_ST_fsm_state25;
    static const sc_lv<88> ap_ST_fsm_state26;
    static const sc_lv<88> ap_ST_fsm_state27;
    static const sc_lv<88> ap_ST_fsm_state28;
    static const sc_lv<88> ap_ST_fsm_state29;
    static const sc_lv<88> ap_ST_fsm_state30;
    static const sc_lv<88> ap_ST_fsm_state31;
    static const sc_lv<88> ap_ST_fsm_state32;
    static const sc_lv<88> ap_ST_fsm_state33;
    static const sc_lv<88> ap_ST_fsm_state34;
    static const sc_lv<88> ap_ST_fsm_state35;
    static const sc_lv<88> ap_ST_fsm_state36;
    static const sc_lv<88> ap_ST_fsm_state37;
    static const sc_lv<88> ap_ST_fsm_state38;
    static const sc_lv<88> ap_ST_fsm_state39;
    static const sc_lv<88> ap_ST_fsm_state40;
    static const sc_lv<88> ap_ST_fsm_state41;
    static const sc_lv<88> ap_ST_fsm_state42;
    static const sc_lv<88> ap_ST_fsm_state43;
    static const sc_lv<88> ap_ST_fsm_state44;
    static const sc_lv<88> ap_ST_fsm_state45;
    static const sc_lv<88> ap_ST_fsm_state46;
    static const sc_lv<88> ap_ST_fsm_state47;
    static const sc_lv<88> ap_ST_fsm_state48;
    static const sc_lv<88> ap_ST_fsm_state49;
    static const sc_lv<88> ap_ST_fsm_state50;
    static const sc_lv<88> ap_ST_fsm_state51;
    static const sc_lv<88> ap_ST_fsm_state52;
    static const sc_lv<88> ap_ST_fsm_state53;
    static const sc_lv<88> ap_ST_fsm_state54;
    static const sc_lv<88> ap_ST_fsm_state55;
    static const sc_lv<88> ap_ST_fsm_state56;
    static const sc_lv<88> ap_ST_fsm_state57;
    static const sc_lv<88> ap_ST_fsm_state58;
    static const sc_lv<88> ap_ST_fsm_state59;
    static const sc_lv<88> ap_ST_fsm_state60;
    static const sc_lv<88> ap_ST_fsm_state61;
    static const sc_lv<88> ap_ST_fsm_state62;
    static const sc_lv<88> ap_ST_fsm_state63;
    static const sc_lv<88> ap_ST_fsm_state64;
    static const sc_lv<88> ap_ST_fsm_state65;
    static const sc_lv<88> ap_ST_fsm_state66;
    static const sc_lv<88> ap_ST_fsm_state67;
    static const sc_lv<88> ap_ST_fsm_state68;
    static const sc_lv<88> ap_ST_fsm_state69;
    static const sc_lv<88> ap_ST_fsm_state70;
    static const sc_lv<88> ap_ST_fsm_state71;
    static const sc_lv<88> ap_ST_fsm_state72;
    static const sc_lv<88> ap_ST_fsm_state73;
    static const sc_lv<88> ap_ST_fsm_state74;
    static const sc_lv<88> ap_ST_fsm_state75;
    static const sc_lv<88> ap_ST_fsm_state76;
    static const sc_lv<88> ap_ST_fsm_state77;
    static const sc_lv<88> ap_ST_fsm_state78;
    static const sc_lv<88> ap_ST_fsm_state79;
    static const sc_lv<88> ap_ST_fsm_state80;
    static const sc_lv<88> ap_ST_fsm_state81;
    static const sc_lv<88> ap_ST_fsm_state82;
    static const sc_lv<88> ap_ST_fsm_state83;
    static const sc_lv<88> ap_ST_fsm_state84;
    static const sc_lv<88> ap_ST_fsm_state85;
    static const sc_lv<88> ap_ST_fsm_state86;
    static const sc_lv<88> ap_ST_fsm_state87;
    static const sc_lv<88> ap_ST_fsm_state88;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<32> ap_const_lv32_31;
    static const sc_lv<32> ap_const_lv32_36;
    static const sc_lv<32> ap_const_lv32_51;
    static const sc_lv<32> ap_const_lv32_2C;
    static const sc_lv<32> ap_const_lv32_4C;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_37;
    static const sc_lv<32> ap_const_lv32_56;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_57;
    static const sc_lv<32> ap_const_lv32_4D;
    static const sc_lv<32> ap_const_lv32_32;
    static const sc_lv<64> ap_const_lv64_3FF0000000000000;
    static const sc_lv<64> ap_const_lv64_BFF0000000000000;
    static const sc_lv<64> ap_const_lv64_4000000000000000;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_2D;
    static const sc_lv<32> ap_const_lv32_52;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<64> ap_const_lv64_4036000000000000;
    static const sc_lv<52> ap_const_lv52_0;
    static const sc_lv<11> ap_const_lv11_0;
    static const sc_lv<32> ap_const_lv32_3F;
    static const sc_lv<32> ap_const_lv32_34;
    static const sc_lv<32> ap_const_lv32_3E;
    static const sc_lv<11> ap_const_lv11_7FF;
    static const sc_lv<11> ap_const_lv11_3C8;
    static const sc_lv<64> ap_const_lv64_7FFFFFFFFFFFFFFF;
    static const sc_lv<11> ap_const_lv11_3FF;
    static const sc_lv<64> ap_const_lv64_8000000000000000;
    static const sc_lv<11> ap_const_lv11_3E4;
    static const sc_lv<11> ap_const_lv11_3E3;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<5> ap_const_lv5_4;
    static const sc_lv<64> ap_const_lv64_0;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_var_for_const2();
    void thread_ap_clk_no_reset_();
    void thread_abst_in_fu_185_p1();
    void thread_and_ln75_fu_209_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state14();
    void thread_ap_CS_fsm_state18();
    void thread_ap_CS_fsm_state19();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state23();
    void thread_ap_CS_fsm_state24();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state45();
    void thread_ap_CS_fsm_state46();
    void thread_ap_CS_fsm_state50();
    void thread_ap_CS_fsm_state51();
    void thread_ap_CS_fsm_state55();
    void thread_ap_CS_fsm_state56();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state77();
    void thread_ap_CS_fsm_state78();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state82();
    void thread_ap_CS_fsm_state83();
    void thread_ap_CS_fsm_state87();
    void thread_ap_CS_fsm_state88();
    void thread_ap_NS_fsm_state8();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_phi_mux_resultf_4_phi_fu_74_p10();
    void thread_ap_predicate_op138_call_state8_state7();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_bitcast_ln112_1_fu_302_p1();
    void thread_bitcast_ln112_fu_292_p1();
    void thread_bitcast_ln84_fu_233_p1();
    void thread_bitcast_ln95_1_fu_323_p1();
    void thread_bitcast_ln95_fu_313_p1();
    void thread_grp_exp_generic_double_s_fu_87_ap_start();
    void thread_grp_fu_112_p0();
    void thread_grp_fu_117_p0();
    void thread_grp_fu_122_p2();
    void thread_grp_fu_127_p2();
    void thread_grp_fu_98_opcode();
    void thread_grp_fu_98_p0();
    void thread_grp_fu_98_p1();
    void thread_icmp_ln10_fu_268_p2();
    void thread_icmp_ln833_1_fu_203_p2();
    void thread_icmp_ln833_fu_191_p2();
    void thread_icmp_ln849_1_fu_223_p2();
    void thread_icmp_ln849_fu_197_p2();
    void thread_icmp_ln9_fu_280_p2();
    void thread_or_ln10_fu_274_p2();
    void thread_or_ln9_fu_286_p2();
    void thread_p_Result_7_fu_249_p3();
    void thread_p_Result_8_fu_177_p3();
    void thread_p_Val2_1_fu_245_p1();
    void thread_p_Val2_s_fu_146_p1();
    void thread_select_ln67_fu_215_p3();
    void thread_select_ln775_fu_306_p3();
    void thread_tmp_V_1_fu_168_p1();
    void thread_tmp_V_2_fu_257_p4();
    void thread_tmp_V_fu_158_p4();
    void thread_trunc_ln368_fu_173_p1();
    void thread_x_3_fu_238_p3();
    void thread_xor_ln112_fu_296_p2();
    void thread_xor_ln84_fu_228_p2();
    void thread_xor_ln95_fu_317_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
